Repository autonomys/astral, pull requests merged in 2022-11, with the labels that each got.

#27 initial structure and add home, blocs and extrinsic pages
  client/codegen.ts
  client/package.json
  client/postcss.config.js
  client/public/index.html
  client/src/App.tsx
  client/src/BlockList/components/BlockList.tsx
  client/src/BlockList/index.tsx
  client/src/BlockList/query.ts
  client/src/ExtrinsicList/components/ExtrinsicList.tsx
  client/src/ExtrinsicList/index.tsx
  client/src/ExtrinsicList/query.ts
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/components/HomeInfoCard.tsx
  client/src/Home/index.tsx
  client/src/common/components/Pagination.tsx
  client/src/common/components/Table.tsx
  client/src/common/components/TableLoadingSkeleton.tsx
  client/src/common/helpers/index.ts
  client/src/common/icons/BlockIcon.tsx
  client/src/common/icons/ClosedWalletIcon.tsx
  client/src/common/icons/CoinIcon.tsx
  client/src/common/icons/DocIcon.tsx
  client/src/common/icons/MaximizeIcon.tsx
  client/src/common/icons/PieChartIcon.tsx
  client/src/common/icons/WalletIcon.tsx
  client/src/common/routes/index.ts
  client/src/components/BlockList/BlockList.tsx
  client/src/components/BlockList/index.tsx
  client/src/components/BlockList/query.ts
  client/src/components/ExtrinsicList/ExtrinsicList.tsx
  client/src/components/ExtrinsicList/index.tsx
  client/src/components/ExtrinsicList/query.ts
  client/src/components/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/index.css
  client/src/layout/components/Container.tsx
  client/src/layout/components/Footer.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/Layout.tsx
  client/src/layout/components/index.ts
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement, ui/ux

#32 Error component
  client/src/BlockList/index.tsx
  client/src/ExtrinsicList/index.tsx
  client/src/Home/index.tsx
  client/src/common/components/ErrorFallback.tsx
Labels: enhancement, ui/ux

#34 feat(extrinsic): add extrinsic details page
  client/package.json
  client/src/App.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Extrinsic/components/Extrinsic.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Extrinsic/query.ts
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/common/routes/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/yarn.lock
Labels: enhancement, ui/ux

#39 Add blockchain history size and space pledged
  squid-blockexplorer/src/blocks.ts
  squid-blockexplorer/src/utils.ts
Labels: S, backend

#38 Update readme
  README.md
  squid-blockexplorer/README.md
Labels: documentation

#44 feat(action): add main deploy action workflow
  .github/workflows/gh-deploy-main.yml
Labels: enhancement, ci / cd

#47 Apply design changes and refactor
  client/package.json
  client/public/index.html
  client/src/Account/components/Account.tsx
  client/src/Account/components/AccountBalancePieChart.tsx
  client/src/Account/components/AccountBalanceStats.tsx
  client/src/Account/components/AccountList.tsx
  client/src/Account/components/AccountTable.tsx
  client/src/Account/query.ts
  client/src/App.tsx
  client/src/Block/components/Block.tsx
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Block/query.ts
  client/src/Event/components/EventList.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Event/query.ts
  client/src/Extrinsic/components/Extrinsic.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Extrinsic/query.ts
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/components/HomeInfoCard.tsx
  client/src/Home/index.tsx
  client/src/common/components/Accordion.tsx
  client/src/common/components/Dropdown.tsx
  client/src/common/components/Pagination.tsx
  client/src/common/components/SearchBar.tsx
  client/src/common/components/Spinner.tsx
  client/src/common/components/Table.tsx
  client/src/common/components/TableLoadingSkeleton.tsx
  client/src/common/components/Tabs.tsx
  client/src/common/helpers/index.ts
  client/src/common/hooks/usePagination.ts
  client/src/common/icons/BlockIcon.tsx
  client/src/common/icons/DocIcon.tsx
  client/src/common/icons/LogoIcon.tsx
  client/src/common/icons/PieChartIcon.tsx
  client/src/common/icons/SubspaceSymbol.tsx
  client/src/common/icons/WalletIcon.tsx
  client/src/common/images/img.png
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/index.css
  client/src/layout/components/Container.tsx
  client/src/layout/components/Footer.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderBackground.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/src/layout/components/Layout.tsx
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement, ui/ux

#48 fix build folder path
  .github/workflows/gh-deploy-main.yml
Labels: bug, ci / cd

#49 fix build folder path
  .github/workflows/gh-deploy-main.yml
Labels: bug, ci / cd

#50 Processing balances refactoring and test
  squid-blockexplorer/src/balances.ts
  squid-blockexplorer/src/balances/constants.ts
  squid-blockexplorer/src/balances/index.ts
  squid-blockexplorer/src/balances/processBalances.ts
  squid-blockexplorer/src/balances/processCall.ts
  squid-blockexplorer/src/balances/processEvent.ts
  squid-blockexplorer/src/balances/saveAccounts.ts
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/balances/types.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/src/test/balances/processBalances.test.ts
  squid-blockexplorer/src/test/balances/processCall.test.ts
  squid-blockexplorer/src/test/balances/processEvent.test.ts
  squid-blockexplorer/src/test/balances/saveAccounts.test.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
Labels: backend

#46 Process blocks refactoring and tests
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/balances.ts
  squid-blockexplorer/src/balances/constants.ts
  squid-blockexplorer/src/balances/index.ts
  squid-blockexplorer/src/balances/processBalances.ts
  squid-blockexplorer/src/balances/processCall.ts
  squid-blockexplorer/src/balances/processEvent.ts
  squid-blockexplorer/src/balances/saveAccounts.ts
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/balances/types.ts
  squid-blockexplorer/src/blocks.ts
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/blocks/processCalls.ts
  squid-blockexplorer/src/blocks/processEvents.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/blocks/types.ts
  squid-blockexplorer/src/blocks/utils.ts
  squid-blockexplorer/src/mocks/BlockHeader.json
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/src/test/balances/processBalances.test.ts
  squid-blockexplorer/src/test/balances/processCall.test.ts
  squid-blockexplorer/src/test/balances/processEvent.test.ts
  squid-blockexplorer/src/test/balances/saveAccounts.test.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
  squid-blockexplorer/src/test/blocks/processBlocks.test.ts
  squid-blockexplorer/src/test/blocks/processCalls.test.ts
  squid-blockexplorer/src/test/blocks/processEvents.test.ts
  squid-blockexplorer/src/test/blocks/storage.test.ts
  squid-blockexplorer/src/test/blocks/utils.test.ts
  squid-blockexplorer/src/utils.ts
  squid-blockexplorer/tsconfig.json
Labels: M, backend

#51 add staging workflow
  .github/workflows/gh-deploy-staging.yml
Labels: enhancement, ci / cd

#58 Update workflow variables and variable name
  .github/workflows/gh-deploy-main.yml
  client/src/App.tsx
  client/src/gql/index.ts
Labels: bug, ci / cd

#57 Add CI badge and adjust coverage
  .github/workflows/build.yaml
  README.md
  squid-blockexplorer/.gitignore
  squid-blockexplorer/.nycrc
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
Labels: documentation, backend, ci / cd

#59 Add readme screenshot
  README.md
Labels: documentation

#61 Fix segments count query
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/blocks/utils.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/test/blocks/storage.test.ts
Labels: bug, backend

#74 Fix hash router
  client/src/App.tsx
Labels: S, ui/ux
