Repository autonomys/astral, pull requests merged in 2022-12, with the labels that each got.

#77 Add logs to blocks processing
  squid-blockexplorer/db/migrations/1669804462948-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/blocks/getEvents.ts
  squid-blockexplorer/src/blocks/getLogs.ts
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/blocks/types.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/model/generated/index.ts
  squid-blockexplorer/src/model/generated/log.model.ts
  squid-blockexplorer/src/test/blocks/getEvents.test.ts
  squid-blockexplorer/src/test/blocks/getLogs.test.ts
  squid-blockexplorer/src/test/blocks/processBlocks.test.ts
  squid-blockexplorer/src/test/blocks/storage.test.ts
Labels: M, backend

#78 Update chain info when new block arrives
  client/src/Home/components/HomeBlockList.tsx
Labels: bug, S, ui/ux

#80 Feat/responsive
  client/.eslintrc
  client/src/Account/components/AccountBalancePieChart.tsx
  client/src/Account/components/AccountBalanceStats.tsx
  client/src/Account/components/AccountDetailsCard.tsx
  client/src/Account/components/AccountDetailsTabs.tsx
  client/src/Account/components/AccountList.tsx
  client/src/Account/components/AccountListCard.tsx
  client/src/Account/components/AccountTable.tsx
  client/src/App.tsx
  client/src/Block/components/Block.tsx
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/components/BlockDetailsLogList.tsx
  client/src/Block/components/BlockDetailsTabs.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Block/components/BlockListCard.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Block/query.ts
  client/src/Event/components/EventList.tsx
  client/src/Event/components/EventListCard.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Extrinsic/components/Extrinsic.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Extrinsic/components/ExtrinsicListCard.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Home/components/HomeBlockCard.tsx
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeChainInfoSkeleton.tsx
  client/src/Home/components/HomeExtrinsicCard.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/index.tsx
  client/src/Log/components/LogDetailsTab.tsx
  client/src/Log/components/LogList.tsx
  client/src/Log/components/LogListCard.tsx
  client/src/Log/components/LogTable.tsx
  client/src/common/components/List.tsx
  client/src/common/components/MobileCard.tsx
  client/src/common/components/SearchBar.tsx
  client/src/common/components/Tabs.tsx
  client/src/common/hooks/useMediaQuery.ts
  client/src/common/routes/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/layout/components/Container.tsx
  client/src/layout/components/Footer.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderBackground.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/src/layout/components/MobileHeader.tsx
  client/tailwind.config.js
Labels: enhancement, ui/ux

#83 feat(favicon): update to new favicon
  client/public/favicon.ico
Labels: enhancement, ui/ux

#85 Update squid dependencies
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/blocks/getLogs.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/account.model.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/model/generated/call.model.ts
  squid-blockexplorer/src/model/generated/event.model.ts
  squid-blockexplorer/src/model/generated/extrinsic.model.ts
  squid-blockexplorer/src/model/generated/log.model.ts
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
  squid-blockexplorer/src/types/calls.ts
  squid-blockexplorer/src/types/constants.ts
  squid-blockexplorer/src/types/events.ts
  squid-blockexplorer/src/types/storage.ts
  squid-blockexplorer/src/types/support.ts
  squid-blockexplorer/src/types/v3.ts
Labels: backend

#91 Add indexes to schema
  squid-blockexplorer/.env
  squid-blockexplorer/db/migrations/1669804462948-Data.js
  squid-blockexplorer/db/migrations/1670569129973-Data.js
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/config.ts
  squid-blockexplorer/src/model/generated/account.model.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/model/generated/extrinsic.model.ts
Labels: backend

#95 implement single query with polling for home page
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/index.tsx
  client/src/Home/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: enhancement, ui/ux

#101 Home page query optimization
  .github/workflows/gh-deploy-main.yml
  client/src/Home/query.ts
  client/src/common/providers/DomainProvider.tsx
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/typing.d.ts
  squid-blockexplorer/Makefile
  squid-blockexplorer/db/migrations/1671003885652-Data.js
  squid-blockexplorer/package.json
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/model/generated/extrinsic.model.ts
  squid-blockexplorer/typegen.json
Labels: enhancement, S, ui/ux, backend

#106 Increase max response size to 5000
  squid-blockexplorer/Makefile
  squid-blockexplorer/package.json
Labels: backend

#109 Add block items counts
  squid-blockexplorer/db/migrations/1671352686402-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/blocks/utils.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/test/blocks/utils.test.ts
Labels: enhancement, backend

#111 Update query for block extrinsics and events count
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/query.ts
  client/src/gql/graphql.ts
Labels: enhancement, S, ui/ux

#112 Gemini 3 adjustments
  squid-blockexplorer/db/migrations/1672121801852-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/balances/processEvent.ts
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/blocks/getLogs.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/extrinsic.model.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
  squid-blockexplorer/src/types/calls.ts
  squid-blockexplorer/src/types/constants.ts
  squid-blockexplorer/src/types/events.ts
  squid-blockexplorer/src/types/storage.ts
  squid-blockexplorer/src/types/v0.ts
  squid-blockexplorer/typegen.json
Labels: enhancement, S, backend

#113 Update migration
  squid-blockexplorer/db/migrations/1672169988223-Data.js
Labels: S, backend

#114 feat(domain): add gemini 3 config
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/layout/components/DomainHeader.tsx
  client/src/layout/config/domain.json
Labels: enhancement, S, ui/ux
