Repository autonomys/astral, pull requests merged in 2023-04, with the labels that each got.

#201 fix(config): action config for pushes to main
  .github/workflows/playwright-main.yml
  .github/workflows/playwright-prs.yml
  client/e2e/singleLog.test.ts
  client/src/gql/index.ts
  client/tailwind.config.js
Labels: bug, ci / cd

#209 feat(export): add export to excel button on list pages
  client/package.json
  client/src/Account/components/AccountList.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Event/components/EventList.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Log/components/LogList.tsx
  client/src/common/components/ExportButton.tsx
  client/src/common/helpers/exportToExcel.ts
  client/yarn.lock
Labels: enhancement, ui/ux

#207 fix(header): dropdown menu close on click
  client/src/layout/components/HeaderDropdownMenu.tsx
Labels: ui/ux

#211 Fix/sort account list by balance
  client/src/Account/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: ui/ux

#213 Add health check service
  .github/workflows/build.yaml
  .github/workflows/gh-container-image.yml
  README.md
  health-check/.dockerignore
  health-check/.env
  health-check/.eslintignore
  health-check/.eslintrc
  health-check/.gitignore
  health-check/Dockerfile
  health-check/README.md
  health-check/entrypoint.sh
  health-check/package-lock.json
  health-check/package.json
  health-check/src/pg.ts
  health-check/src/prometheus.ts
  health-check/tsconfig.json
Labels: backend

#228 Use `crypto.timingSafeEqual` to compare secret values
  health-check/.eslintrc
  health-check/src/pg.ts
  health-check/src/prometheus.ts
  health-check/src/utils.ts
Labels: backend

#227 Add `SECRET` env to the readme
  health-check/README.md
Labels: backend

#219 fix(json): show just objects below 5 items
  client/src/common/components/Arguments.tsx
Labels: ui/ux

#222 fix(extrinsic): show correct module and call
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/common/components/List.tsx
Labels: ui/ux

#221 fix(log): show engine and data values
  client/src/Log/components/LogDetailsCard.tsx
  client/src/Log/components/LogTable.tsx
  client/src/Log/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: ui/ux

#220 fix(block): add correct extrinsic and event list counts
  client/src/Block/components/Block.tsx
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockDetailsTabs.tsx
  client/src/Block/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/gql/index.ts
Labels: ui/ux

#231 Remove `Success` column and use `Status` instead
  client/src/Extrinsic/components/ExtrinsicTable.tsx
Labels: ui/ux

#230 Fix download button dark mode style
  client/src/common/components/ExportButton.tsx
Labels: ui/ux

#229 Fix env var name
  health-check/src/pg.ts
  health-check/src/prometheus.ts
Labels: backend

#233 feat(search): allow search by hash for block and extrinsic
  client/package.json
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/query.ts
  client/src/Extrinsic/query.ts
  client/src/common/components/SearchBar.tsx
  client/src/common/hooks/useSearch.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/gql/index.ts
  client/yarn.lock
Labels: enhancement, ui/ux

#242 feat(result): add search result page for when we get more than one result
  client/src/App.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Extrinsic/query.ts
  client/src/common/hooks/useSearch.ts
  client/src/common/queries/index.ts
  client/src/common/routes/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/layout/components/SearchResult.tsx
Labels: enhancement, ui/ux

#243 Fix Extrinsics and Events IDs, sort list items by ID
  client/src/Account/query.ts
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/query.ts
  client/src/Event/components/EventListCard.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Event/query.ts
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicListCard.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Extrinsic/query.ts
  client/src/Home/components/HomeExtrinsicCard.tsx
  client/src/Home/query.ts
  client/src/Home/test/mocks.ts
  client/src/Log/components/LogDetailsEventList.tsx
  client/src/Log/query.ts
  client/src/common/components/EventCard.tsx
  client/src/common/components/ExtrinsicCard.tsx
  client/src/common/helpers/generateColumns.tsx
  client/src/common/tests/mocks/SearchQueryMocks.ts
Labels: ui/ux

#249 Add Gemini-3d
  client/src/layout/config/chains.json
  squid-blockexplorer/api.md
Labels: ui/ux

#205 Add separate reward event entity
  squid-blockexplorer/Makefile
  squid-blockexplorer/README.md
  squid-blockexplorer/db/migrations/1681818800173-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/blocks/getEvents.ts
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/blocks/processCalls.ts
  squid-blockexplorer/src/blocks/processEvents.ts
  squid-blockexplorer/src/blocks/types.ts
  squid-blockexplorer/src/blocks/utils.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/account.model.ts
  squid-blockexplorer/src/model/generated/index.ts
  squid-blockexplorer/src/model/generated/rewardEvent.model.ts
  squid-blockexplorer/src/test/blocks/processBlocks.test.ts
  squid-blockexplorer/src/test/blocks/processCalls.test.ts
  squid-blockexplorer/src/test/blocks/processEvents.test.ts
  squid-blockexplorer/src/test/blocks/utils.test.ts
Labels: backend

#255 Update calc history size for gemini 3d
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/blocks/utils.ts
Labels: backend

#258 Include reward events
  health-check/.env
  squid-blockexplorer/api.md
  squid-blockexplorer/db/migrations/1681818800173-Data.js
  squid-blockexplorer/db/migrations/1682581659497-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/balances/processEvent.ts
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/blocks/getLogs.ts
  squid-blockexplorer/src/blocks/processEvents.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
  squid-blockexplorer/src/test/blocks/processEvents.test.ts
  squid-blockexplorer/src/types/calls.ts
  squid-blockexplorer/src/types/constants.ts
  squid-blockexplorer/src/types/events.ts
  squid-blockexplorer/src/types/storage.ts
  squid-blockexplorer/src/types/v1.ts
Labels: backend

#257 fix(home): extrinsic list timestamp
  client/src/Account/test/AccountBalanceStats.test.tsx
  client/src/Account/test/AccountDetailsCard.test.tsx
  client/src/Account/test/AccountTable.test.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: bug, ui/ux
