Repository autonomys/astral, pull requests merged in 2023-05, with the labels that each got.

#261 Fix migration
  squid-blockexplorer/db/migrations/1682581659497-Data.js
  squid-blockexplorer/db/migrations/1682937572115-Data.js
Labels: backend

#262 Add custom resolvers
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/server-extension/resolvers/index.ts
Labels: backend

#263 fix(account): add rewards list path
  client/src/App.tsx
Labels: bug

#260 Feat/add table filtering
  client/package.json
  client/src/Account/components/AccountExtrinsicFilterDropdown.tsx
  client/src/Account/components/AccountExtrinsicList.tsx
  client/src/Account/components/AccountExtrinsicTable.tsx
  client/src/Account/components/index.ts
  client/src/Account/query.ts
  client/src/Event/components/EventList.tsx
  client/src/Event/components/EventListFilter.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Event/query.ts
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Extrinsic/components/ExtrinsicListFilter.tsx
  client/src/Extrinsic/query.ts
  client/src/Log/components/LogList.tsx
  client/src/Log/components/LogListFilter.tsx
  client/src/Log/query.ts
  client/src/common/components/Accordion.tsx
  client/src/common/components/BasicDatepicker.tsx
  client/src/common/components/Dropdown.tsx
  client/src/common/components/FilterForm.tsx
  client/src/common/components/Table.tsx
  client/src/common/constants/index.ts
  client/src/common/icons/EmptyCircleIcon.tsx
  client/src/common/icons/FilterIcon.tsx
  client/src/common/icons/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/layout/components/Container.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement, ui/ux

#268 Update events processing
  squid-blockexplorer/src/blocks/processEvents.ts
  squid-blockexplorer/src/test/blocks/processEvents.test.ts
Labels: backend

#267 fix(search): fix issues searching anything other than hashes
  client/src/common/components/SearchBar.tsx
  client/src/common/hooks/useSearch.ts
  client/src/common/queries/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: bug, ui/ux

#269 Save reward event as both Event and RewardEvent
  squid-blockexplorer/src/blocks/processEvents.ts
  squid-blockexplorer/src/test/blocks/processEvents.test.ts
Labels: backend

#254 feat(search): add not result found to empty searches
  client/src/App.tsx
  client/src/common/hooks/useSearch.ts
  client/src/common/routes/index.ts
  client/src/layout/components/NotResultsFound.tsx
Labels: enhancement

#274 Feat/add result table for conflicting event and extrinsic
  client/src/common/helpers/formatSearchResult.ts
  client/src/common/hooks/useSearch.ts
  client/src/common/queries/index.ts
  client/src/common/routes/index.ts
  client/src/gql/index.ts
  client/src/layout/components/ExtrinsicAndEventResult/ExtrinsicAndEventResultCard.tsx
  client/src/layout/components/ExtrinsicAndEventResult/index.tsx
  client/src/layout/components/SearchResult.tsx
  client/src/layout/components/index.ts
Labels: enhancement

#279 Fix/filter minor issues
  client/package.json
  client/src/common/components/BasicDatepicker.tsx
  client/src/common/components/FilterForm.tsx
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: ui/ux

#253 feat(gemini2): add static page for gemini 2 routes
  client/src/Account/components/OldAccount.tsx
  client/src/Account/components/OldAccountBalancePieChart.tsx
  client/src/Account/components/OldAccountBalanceStats.tsx
  client/src/Account/components/OldAccountDetailsCard.tsx
  client/src/Account/components/OldAccountDetailsTabs.tsx
  client/src/Account/components/OldAccountExtrinsicList.tsx
  client/src/Account/components/index.ts
  client/src/App.tsx
  client/src/common/routes/index.ts
  client/src/layout/components/Gemini2Static.tsx
Labels: enhancement

#278 feat(pagination): refactor pagination
  client/package.json
  client/src/Account/components/AccountExtrinsicList.tsx
  client/src/Account/components/AccountList.tsx
  client/src/Account/components/AccountRewardList.tsx
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Event/components/EventList.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Log/components/LogList.tsx
  client/src/common/components/ExportButton.tsx
  client/src/common/components/Pagination.tsx
  client/src/common/hooks/usePagination.ts
  client/src/common/tests/Pagination.test.tsx
  client/src/common/tests/__snapshots__/Pagination.test.tsx.snap
  client/src/gql/index.ts
  client/src/layout/components/MobileHeader.tsx
  client/yarn.lock
Labels: enhancement

#282 Fix typo and add `extrinsicsRoot` to a block
  squid-blockexplorer/db/migrations/1684128550726-Data.js
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/model/generated/block.model.ts
Labels: bug, backend

#283 Update gemini 3d api endpoint
  client/src/gql/graphql.ts
  client/src/layout/config/chains.json
  squid-blockexplorer/api.md
Labels: ui/ux

#284 fix(runtime): update runtime version
  squid-blockexplorer/db/migrations/1684420711430-Data.js
  squid-blockexplorer/src/balances/storage.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/test/balances/storage.test.ts
  squid-blockexplorer/src/types/calls.ts
  squid-blockexplorer/src/types/constants.ts
  squid-blockexplorer/src/types/events.ts
  squid-blockexplorer/src/types/storage.ts
  squid-blockexplorer/src/types/v2.ts
Labels: bug, backend

#285 fix(balance): make sure it handles both runtimes
  squid-blockexplorer/src/balances/storage.ts
Labels: bug, backend

#288 feat(header): update navigation header
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/gql/index.ts
  client/src/layout/components/Container.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/src/layout/components/index.ts
Labels: enhancement

#286 (feat): use backend queries for modules and logTypes
  client/src/Event/components/EventList.tsx
  client/src/Event/components/EventListFilter.tsx
  client/src/Event/query.ts
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Extrinsic/components/ExtrinsicListFilter.tsx
  client/src/Extrinsic/query.ts
  client/src/Log/components/LogList.tsx
  client/src/Log/components/LogListFilter.tsx
  client/src/Log/query.ts
  client/src/common/components/FilterForm.tsx
  client/src/common/constants/index.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: enhancement
