Repository autonomys/astral, pull requests merged in 2023-01, with the labels that each got.

#118 Remove `REACT_APP_GRAPHQL_API_URL` env variable
  .github/workflows/build.yaml
  .github/workflows/gh-deploy-main.yml
  client/.env.sample
  client/codegen.ts
  client/src/common/providers/DomainProvider.tsx
  client/src/layout/components/DomainHeader.tsx
  client/typing.d.ts
Labels: S, ui/ux

#117 Remove Home page Latest block `Status` column
  client/src/Home/components/HomeBlockList.tsx
Labels: enhancement, S, ui/ux

#120 fix(home): have error fallback for entire page
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/index.tsx
Labels: enhancement, ui/ux

#121 fix(responsive): fix responsive issue on home cards
  client/package.json
  client/src/App.tsx
  client/src/Home/components/HomeBlockCard.tsx
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeCards.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/components/HomeInfoCard.tsx
  client/src/common/components/SearchBar.tsx
  client/src/common/components/Table.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/yarn.lock
Labels: bug, ui/ux

#127 Fix/extrinsic event account extrinsic
  client/src/Account/components/Account.tsx
  client/src/Account/components/AccountDetailsTabs.tsx
  client/src/Extrinsic/components/Extrinsic.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/query.ts
  client/src/common/components/Tabs.tsx
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
Labels: bug, ui/ux

#128 fix(search): to allow 1 digit number search
  client/src/common/components/SearchBar.tsx
Labels: bug, ui/ux

#143 fix(backend): update create extrinsic to use call args
  squid-blockexplorer/src/blocks/utils.ts
Labels: backend

#142 fix(ui): fix various ui issues
  client/src/Account/components/AccountBalancePieChart.tsx
  client/src/Account/components/AccountDetailsTabs.tsx
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockDetailsLogList.tsx
  client/src/Block/components/BlockDetailsTabs.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Block/query.ts
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Extrinsic/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/gql/index.ts
  client/src/layout/components/MobileHeader.tsx
Labels: enhancement, ui/ux

#144 Fix/pagination
  client/src/Account/components/AccountList.tsx
  client/src/Account/components/AccountTable.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Event/components/EventList.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Log/components/LogList.tsx
  client/src/common/constants/index.ts
Labels: bug, ui/ux
