Repository autonomys/astral, pull requests merged in 2023-03, with the labels that each got.

#167 UI adjustments
  client/codegen.ts
  client/package.json
  client/src/App.tsx
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Home/components/HomeCards.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeInfoCard.tsx
  client/src/common/providers/ChainProvider.tsx
  client/src/common/providers/DomainProvider.tsx
  client/src/index.tsx
  client/src/layout/components/DomainHeader.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/config/chains.json
  squid-blockexplorer/Dockerfile
Labels: enhancement, ui/ux

#169 Add block author
  squid-blockexplorer/db/migrations/1677752097661-Data.js
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/schema.graphql
  squid-blockexplorer/src/blocks/getLogs.ts
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/blocks/types.ts
  squid-blockexplorer/src/blocks/utils.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/model/generated/block.model.ts
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/src/test/blocks/getLogs.test.ts
  squid-blockexplorer/src/test/blocks/processBlocks.test.ts
  squid-blockexplorer/src/test/blocks/utils.test.ts
  squid-blockexplorer/src/types/constants.ts
  squid-blockexplorer/src/types/events.ts
  squid-blockexplorer/src/types/storage.ts
  squid-blockexplorer/src/types/v0.ts
Labels: enhancement, backend

#180 Save block author before saving block
  squid-blockexplorer/.gitignore
  squid-blockexplorer/src/blocks/processBlocks.ts
  squid-blockexplorer/src/test/blocks/processBlocks.test.ts
Labels: bug, backend

#176 Feat/url chain specific
  client/src/Account/components/AccountExtrinsicList.tsx
  client/src/Account/components/AccountListCard.tsx
  client/src/Account/components/AccountTable.tsx
  client/src/App.tsx
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockDetailsLogList.tsx
  client/src/Block/components/BlockListCard.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Event/components/EventListCard.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicListCard.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Home/components/HomeBlockCard.tsx
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeExtrinsicCard.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Log/components/LogListCard.tsx
  client/src/Log/components/LogTable.tsx
  client/src/common/components/HeaderBlockLink.tsx
  client/src/common/components/SearchBar.tsx
  client/src/common/helpers/generateColumns.tsx
  client/src/common/hooks/useSafeLocalStorage.ts
  client/src/common/hooks/useSearch.ts
  client/src/common/hooks/useTheme.ts
  client/src/common/providers/ChainProvider.tsx
  client/src/common/routes/index.ts
  client/src/gql/index.ts
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/src/layout/config/chains.json
Labels: enhancement, ui/ux

#119 Introduce end-to-end tests
  .github/workflows/build.yaml
  .github/workflows/gh-container-image.yml
  .github/workflows/gh-deploy-staging.yml
  squid-blockexplorer/.env
  squid-blockexplorer/.gitignore
  squid-blockexplorer/.taprc
  squid-blockexplorer/Makefile
  squid-blockexplorer/README.md
  squid-blockexplorer/devnet/docker-compose.yml
  squid-blockexplorer/e2e_testing.md
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/e2e/balance.e2e.ts
  squid-blockexplorer/src/e2e/block.e2e.ts
  squid-blockexplorer/src/e2e/queries.ts
  squid-blockexplorer/src/e2e/types.ts
  squid-blockexplorer/src/e2e/utils.ts
Labels: M, backend

#183 fix(comments): add legacy routing and naming presentation
  client/src/App.tsx
  client/src/gql/graphql.ts
  client/src/gql/index.ts
  client/src/layout/config/chains.json
Labels: enhancement, ui/ux

#185 Squid improvements
  squid-blockexplorer/Makefile
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/blocks/index.ts
  squid-blockexplorer/src/blocks/storage.ts
  squid-blockexplorer/src/mocks/mocks.ts
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/src/test/blocks/storage.test.ts
Labels: backend

#186 Minor processor refactoring
  squid-blockexplorer/src/processor.ts
  squid-blockexplorer/typegen.json
Labels: backend

#190 Fix/site description
  client/public/index.html
Labels: S, ui/ux

#192 fix(compose): update number of max connections and lower scan-start-value
  squid-blockexplorer/devnet/docker-compose.yml
Labels: backend

#189 fix(apollo): add retry using apollo link from
  client/src/common/providers/ChainProvider.tsx
Labels: bug, ui/ux

#199 Feat/add block author
  client/src/Block/components/BlockAuthor.tsx
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/components/BlockListCard.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Block/query.ts
  client/src/gql/gql.ts
  client/src/gql/graphql.ts
  client/src/gql/index.ts
Labels: enhancement

#200 fix(url): update selected network to url matching network if is diffe…
  client/src/App.tsx
  client/src/layout/components/Layout.tsx
Labels: bug, ui/ux

#124 Feat/e2e test
  .github/workflows/build.yaml
  .github/workflows/gh-deploy-main.yml
  .github/workflows/playwright.yml
  client/.gitignore
  client/e2e/accounts.test.ts
  client/e2e/blocks.test.ts
  client/e2e/home.test.ts
  client/e2e/singleAccount.test.ts
  client/e2e/singleBlock.test.ts
  client/e2e/singleEvent.test.ts
  client/e2e/singleLog.test.ts
  client/package.json
  client/playwright.config.ts
  client/src/Block/components/BlockTable.tsx
  client/src/Event/components/EventDetailsCard.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Home/components/HomeBlockList.tsx
  client/src/Log/components/LogTable.tsx
  client/src/common/components/Arguments.tsx
  client/tsconfig.json
  client/typing.d.ts
  client/yarn.lock
Labels: enhancement, ui/ux
