Repository autonomys/astral, pull requests merged in 2023-02, with the labels that each got.

#157 Fix/UI issues
  .DS_Store
  client/public/favicon.ico
  client/src/Account/components/AccountBalancePieChart.tsx
  client/src/Account/components/AccountBalanceStats.tsx
  client/src/Account/components/AccountDetailsCard.tsx
  client/src/Account/components/AccountDetailsTabs.tsx
  client/src/Account/components/AccountExtrinsicList.tsx
  client/src/Account/components/AccountList.tsx
  client/src/Account/components/AccountTable.tsx
  client/src/App.tsx
  client/src/Block/components/BlockDetailsCard.tsx
  client/src/Block/components/BlockDetailsEventList.tsx
  client/src/Block/components/BlockDetailsExtrinsicList.tsx
  client/src/Block/components/BlockDetailsLogList.tsx
  client/src/Block/components/BlockDetailsTabs.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Block/components/BlockTable.tsx
  client/src/Event/components/EventDetailsCard.tsx
  client/src/Event/components/EventDetailsTab.tsx
  client/src/Event/components/EventList.tsx
  client/src/Event/components/EventListCard.tsx
  client/src/Event/components/EventTabDescription.tsx
  client/src/Event/components/EventTable.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsEventList.tsx
  client/src/Extrinsic/components/ExtrinsicDetailsTab.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Extrinsic/components/ExtrinsicTable.tsx
  client/src/Home/components/HomeBlockList.tsx
  client/src/Home/components/HomeChainInfo.tsx
  client/src/Home/components/HomeExtrinsicList.tsx
  client/src/Home/components/HomeInfoCard.tsx
  client/src/Log/components/LogDetailsCard.tsx
  client/src/Log/components/LogDetailsTab.tsx
  client/src/Log/components/LogList.tsx
  client/src/Log/components/LogTable.tsx
  client/src/common/components/Dropdown.tsx
  client/src/common/components/List.tsx
  client/src/common/components/MobileCard.tsx
  client/src/common/components/Pagination.tsx
  client/src/common/components/SearchBar.tsx
  client/src/common/components/Table.tsx
  client/src/common/components/Tabs.tsx
  client/src/gql/index.ts
  client/src/layout/components/Footer.tsx
  client/src/layout/components/Header.tsx
  client/src/layout/components/HeaderBackground.tsx
  client/src/layout/components/HeaderChainDropdown.tsx
  client/src/layout/components/HeaderDropdownMenu.tsx
  client/src/layout/components/MobileHeader.tsx
  client/tailwind.config.js
Labels: ui/ux

#158 Update not found, error, and loading components
  client/package.json
  client/src/Account/components/Account.tsx
  client/src/Account/components/AccountList.tsx
  client/src/App.tsx
  client/src/Block/components/Block.tsx
  client/src/Block/components/BlockList.tsx
  client/src/Event/components/Event.tsx
  client/src/Event/components/EventList.tsx
  client/src/Extrinsic/components/Extrinsic.tsx
  client/src/Extrinsic/components/ExtrinsicList.tsx
  client/src/Home/index.tsx
  client/src/Log/components/Log.tsx
  client/src/Log/components/LogList.tsx
  client/src/common/components/ArrowButton.tsx
  client/src/common/components/ErrorFallback.stories.tsx
  client/src/common/components/ErrorFallback.tsx
  client/src/common/components/ErrorFallback/AstronautImage.tsx
  client/src/common/components/ErrorFallback/ErrorFallback.stories.tsx
  client/src/common/components/ErrorFallback/index.tsx
  client/src/common/components/Spinner.tsx
  client/src/common/components/Spinner/Loader_Light.json
  client/src/common/components/Spinner/Spinner.stories.tsx
  client/src/common/components/Spinner/index.tsx
  client/src/common/components/index.ts
  client/src/layout/components/Container.tsx
  client/src/layout/components/NotFound.tsx
  client/src/layout/components/NotFound/NotFoundImage.tsx
  client/src/layout/components/NotFound/index.tsx
  client/yarn.lock
Labels: enhancement, ui/ux

#159 Add identicon icons for accounts
  client/package.json
  client/src/Account/components/AccountDetailsCard.tsx
  client/src/Account/components/AccountListCard.tsx
  client/src/Account/components/AccountTable.tsx
  client/yarn.lock
Labels: enhancement, ui/ux

#162 Update Subsquid dependencies (`main` branch)
  .github/workflows/build.yaml
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/mocks/mocks.ts
Labels: backend

#161 Update Subsquid dependencies for Gemini-2 squid
  .github/workflows/build.yaml
  squid-blockexplorer/package-lock.json
  squid-blockexplorer/package.json
  squid-blockexplorer/src/mocks/mocks.ts
Labels: backend
