Repository autonomys/astral, pull requests merged in 2024-10, with the labels that each got.

#862 Update privacy policy link
  explorer/src/components/common/CookieBanner.tsx
  explorer/src/constants/routes.ts
Labels: enhancement, Review effort [1-5]: 2

#806 Turn the name and address saved in address book, link to account page
  explorer/src/components/WalletSideKick/AccountPreferencesModal.tsx
Labels: enhancement, Review effort [1-5]: 2

#865 Improve Consensus Sub Query
  indexers/db/metadata/databases/gemini_3h/tables/consensus_log_kinds.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_logs.yaml
  indexers/gemini-3h/consensus/schema.graphql
  indexers/gemini-3h/consensus/src/mappings/db.ts
  indexers/gemini-3h/consensus/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/consensus/src/mappings/types.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#859 Improve staking sub query
  docker-compose.yml
  indexers/db/metadata/databases/gemini_3h/tables/staking_accounts.yaml
  indexers/db/metadata/databases/gemini_3h/tables/staking_deposits.yaml
  indexers/db/metadata/databases/gemini_3h/tables/staking_domains.yaml
  indexers/db/metadata/databases/gemini_3h/tables/staking_nominators.yaml
  indexers/db/metadata/databases/gemini_3h/tables/staking_operators.yaml
  indexers/db/metadata/databases/gemini_3h/tables/staking_withdrawals.yaml
  indexers/db/metadata/databases/gemini_3h/tables/tables.yaml
  indexers/gemini-3h/staking/project.ts
  indexers/gemini-3h/staking/schema.graphql
  indexers/gemini-3h/staking/src/mappings/constants.ts
  indexers/gemini-3h/staking/src/mappings/db.ts
  indexers/gemini-3h/staking/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/staking/src/mappings/models.ts
  indexers/gemini-3h/staking/src/mappings/types.ts
  indexers/gemini-3h/staking/src/mappings/utils.ts
Labels: enhancement, Review effort [1-5]: 5, configuration changes

#867 Add sortId with fix length to be able to sort entry id correctly
  indexers/gemini-3h/consensus/schema.graphql
  indexers/gemini-3h/consensus/src/mappings/db.ts
  indexers/gemini-3h/consensus/src/mappings/utils.ts
Labels: enhancement, Review effort [1-5]: 3, other, indexer

#871 Add node to setup
  .env
  docker-compose.yml
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#873 Fix testnet rewards label and date format
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
Labels: Review effort [1-5]: 2, Bug fix

#868 Implement auto sdk 0.6.5 in indexers
  indexers/gemini-3g/testnet-rewards/package.json
  indexers/gemini-3h/accounts/package.json
  indexers/gemini-3h/consensus/package.json
  indexers/gemini-3h/consensus/src/mappings/helper.ts
  indexers/gemini-3h/consensus/src/mappings/utils.ts
  indexers/yarn.lock
Labels: enhancement, Review effort [1-5]: 2, dependencies

#878 ## Fix end of gem2 date range
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
Labels: Review effort [1-5]: 1, Bug fix

#876 Sub query setup improvements
  .env
  docker-compose.yml
  indexers/Caddyfile
  indexers/package.json
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#877 Add ToS to the farming downloads page
  explorer/src/components/Farming/index.tsx
Labels: enhancement, Review effort [1-5]: 2

#882 Update to auto-sdk 0.6.7
  indexers/gemini-3g/testnet-rewards/package.json
  indexers/gemini-3g/testnet-rewards/src/mappings/utils.ts
  indexers/gemini-3h/consensus/package.json
  indexers/gemini-3h/consensus/src/mappings/db.ts
  indexers/gemini-3h/consensus/src/mappings/helper.ts
  indexers/gemini-3h/consensus/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/consensus/src/mappings/utils.ts
  indexers/gemini-3h/leaderboard/src/mappings/helper.ts
  indexers/gemini-3h/leaderboard/src/mappings/utils.ts
  indexers/gemini-3h/staking/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/staking/src/mappings/utils.ts
  indexers/yarn.lock
Labels: enhancement, Review effort [1-5]: 3, dependencies

#881 Merge accounts and consensus sub query
  .env
  docker-compose.prod.yml
  docker-compose.yml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_accounts.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_balance_histories.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_rewards.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_transfers.yaml
  indexers/db/metadata/databases/gemini_3h/tables/tables.yaml
  indexers/gemini-3g/testnet-rewards/package.json
  indexers/gemini-3g/testnet-rewards/src/mappings/utils.ts
  indexers/gemini-3h/accounts/.env.develop
  indexers/gemini-3h/accounts/.gitignore
  indexers/gemini-3h/accounts/LICENSE
  indexers/gemini-3h/accounts/README.md
  indexers/gemini-3h/accounts/package.json
  indexers/gemini-3h/accounts/project.ts
  indexers/gemini-3h/accounts/schema.graphql
  indexers/gemini-3h/accounts/src/index.ts
  indexers/gemini-3h/accounts/src/mappings/db.ts
  indexers/gemini-3h/accounts/src/mappings/helper.ts
  indexers/gemini-3h/accounts/src/mappings/utils.ts
  indexers/gemini-3h/accounts/tsconfig.json
  indexers/gemini-3h/consensus/package.json
  indexers/gemini-3h/consensus/project.ts
  indexers/gemini-3h/consensus/schema.graphql
  indexers/gemini-3h/consensus/src/mappings/db.ts
  indexers/gemini-3h/consensus/src/mappings/helper.ts
  indexers/gemini-3h/consensus/src/mappings/mappingAccountHandlers.ts
  indexers/gemini-3h/consensus/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/consensus/src/mappings/utils.ts
  indexers/gemini-3h/leaderboard/project.ts
  indexers/gemini-3h/leaderboard/src/mappings/helper.ts
  indexers/gemini-3h/leaderboard/src/mappings/utils.ts
  indexers/gemini-3h/staking/project.ts
  indexers/gemini-3h/staking/src/mappings/mappingHandlers.ts
  indexers/gemini-3h/staking/src/mappings/utils.ts
  indexers/yarn.lock
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#885 Improve archive history size icon
  explorer/src/components/icons/ArchivedHistoryIcon.tsx
Labels: enhancement, Review effort [1-5]: 4

#886 Implement Auto-SDK 0.6.8 in indexers
  indexers/gemini-3g/testnet-rewards/package.json
  indexers/gemini-3h/consensus/package.json
  indexers/gemini-3h/consensus/src/mappings/helper.ts
  indexers/gemini-3h/consensus/src/mappings/mappingHandlers.ts
  indexers/yarn.lock
Labels: Review effort [1-5]: 3

#887 Add missing hasura permissions for sortId
  indexers/db/metadata/databases/gemini_3h/tables/consensus_blocks.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_event_modules.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_events.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_extrinsic_modules.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_extrinsics.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_logs.yaml
  indexers/db/metadata/databases/gemini_3h/tables/tables.yaml
Labels: Review effort [1-5]: 3

#889 Fix gemini3 end date
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
Labels: Review effort [1-5]: 1

#890 Sync main with production
  explorer/.env.sample
  explorer/gql/gql.ts
  explorer/gql/graphql.ts
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
  explorer/src/components/WalletSideKick/Actions/ClaimStakingToken.tsx
  explorer/src/components/WalletSideKick/Actions/ConnectDiscord.tsx
  explorer/src/components/WalletSideKick/Actions/JoinDiscord.tsx
  explorer/src/components/WalletSideKick/Actions/VerifyWalletOwnership.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/WalletSideKick/query.ts
  explorer/src/components/common/StyledButton.tsx
  explorer/src/components/icons/ArchivedHistoryIcon.tsx
  explorer/src/utils/auth/providers/discord.ts
  explorer/src/utils/auth/providers/subspace.ts
  explorer/src/utils/auth/vcs/discord/index.ts
  explorer/src/utils/auth/vcs/discord/role-farmer.ts
  explorer/src/utils/auth/vcs/discord/role-nominator.ts
  explorer/src/utils/auth/vcs/discord/role-operator.ts
  explorer/src/utils/auth/vcs/subspace/events-farmer.ts
  explorer/src/utils/auth/vcs/subspace/index.ts
  explorer/src/utils/queryGraphqlServer.ts
  indexers/db/metadata/databases/gemini_3h/tables/consensus_blocks.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_event_modules.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_events.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_extrinsic_modules.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_extrinsics.yaml
  indexers/db/metadata/databases/gemini_3h/tables/consensus_logs.yaml
  indexers/db/metadata/databases/gemini_3h/tables/tables.yaml
  indexers/gemini-3g/testnet-rewards/package.json
  indexers/gemini-3h/consensus/package.json
  indexers/gemini-3h/consensus/src/mappings/helper.ts
  indexers/gemini-3h/consensus/src/mappings/mappingHandlers.ts
  indexers/yarn.lock
Labels: Review effort [1-5]: 4

#892 Add a fix for old event that don't have amount arg
  indexers/gemini-3h/leaderboard/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 2

#893 Add Taurus indexers - Part 1
  .vscode/astral.code-workspace
  indexers/lerna.json
  indexers/package.json
  indexers/taurus/README.md
  indexers/taurus/consensus/.gitignore
  indexers/taurus/consensus/LICENSE
  indexers/taurus/consensus/README.md
  indexers/taurus/consensus/gemini3h.jsonl
  indexers/taurus/consensus/package.json
  indexers/taurus/consensus/project.ts
  indexers/taurus/consensus/schema.graphql
  indexers/taurus/consensus/src/index.ts
  indexers/taurus/consensus/src/mappings/db.ts
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingAccountHandlers.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
  indexers/taurus/consensus/src/mappings/types.ts
  indexers/taurus/consensus/src/mappings/utils.ts
  indexers/taurus/consensus/tsconfig.json
  indexers/taurus/consensus/typegen.json
  indexers/taurus/leaderboard/.gitignore
  indexers/taurus/leaderboard/LICENSE
  indexers/taurus/leaderboard/README.md
  indexers/taurus/leaderboard/package.json
  indexers/taurus/leaderboard/project.ts
  indexers/taurus/leaderboard/schema.graphql
  indexers/taurus/leaderboard/src/index.ts
  indexers/taurus/leaderboard/src/mappings/db.ts
  indexers/taurus/leaderboard/src/mappings/helper.ts
  indexers/taurus/leaderboard/src/mappings/mappingHandlers.ts
  indexers/taurus/leaderboard/tsconfig.json
  indexers/taurus/yarn.lock
Labels: Review effort [1-5]: 4

#896 Implement taurus in explorer
  explorer/gql/graphql.ts
  explorer/package.json
  explorer/src/app/[chain]/consensus/accounts/[accountId]/image/route.tsx
  explorer/src/components/Consensus/Account/Account.tsx
  explorer/src/components/Consensus/Account/AccountBalancePieChart.tsx
  explorer/src/components/Consensus/Account/AccountBalanceStats.tsx
  explorer/src/components/Consensus/Account/AccountDetailsCard.tsx
  explorer/src/components/Consensus/Account/AccountGraphs.tsx
  explorer/src/components/Consensus/Account/AccountRewardList.tsx
  explorer/src/components/Consensus/Account/query.ts
  explorer/src/components/Consensus/Block/Block.tsx
  explorer/src/components/Consensus/Block/BlockDetailsCard.tsx
  explorer/src/components/Consensus/Block/BlockDetailsLogList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsTabs.tsx
  explorer/src/components/Consensus/Block/query.ts
  explorer/src/components/Consensus/Event/Event.tsx
  explorer/src/components/Consensus/Event/EventDetailsCard.tsx
  explorer/src/components/Consensus/Event/query.ts
  explorer/src/components/Consensus/Extrinsic/Extrinsic.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsCard.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsEventList.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsTab.tsx
  explorer/src/components/Consensus/Extrinsic/query.ts
  explorer/src/components/Consensus/Log/Log.tsx
  explorer/src/components/Consensus/Log/LogDetailsCard.tsx
  explorer/src/components/Consensus/Log/LogDetailsEventList.tsx
  explorer/src/components/Consensus/Log/LogDetailsTab.tsx
  explorer/src/components/Consensus/Log/query.ts
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/common/EventCard.tsx
  explorer/src/constants/indexers.ts
  explorer/src/hooks/useConsensusData.ts
  explorer/src/hooks/useTxHelper.ts
  explorer/src/providers/WalletProvider.tsx
  explorer/src/utils/chainStateParsing.ts
  explorer/yarn.lock
Labels: Review effort [1-5]: 4

#897 add monitoring to subql stack
  .env
  docker-compose.prod.yml
Labels: Review effort [1-5]: 3

#899 Add consensus related tasks to taskboard
  .env
  .gitignore
  indexers/db/.env.sample
  indexers/db/metadata/databases/taurus/tables/consensus_account_histories.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_account_profiles.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_account_rewards.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_accounts.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_blocks.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_event_modules.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_events.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_extrinsic_modules.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_extrinsics.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_log_kinds.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_logs.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_rewards.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_sections.yaml
  indexers/db/metadata/databases/taurus/tables/consensus_transfers.yaml
  indexers/db/migrations/taurus/1730310914662_alter_table_consensus_sections_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310914662_alter_table_consensus_sections_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730310946777_alter_table_consensus_event_modules_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310946777_alter_table_consensus_event_modules_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730310960555_alter_table_consensus_extrinsic_modules_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310960555_alter_table_consensus_extrinsic_modules_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730310972982_alter_table_consensus_accounts_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310972982_alter_table_consensus_accounts_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730310983740_alter_table_consensus_account_profiles_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310983740_alter_table_consensus_account_profiles_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730310997319_alter_table_consensus_account_rewards_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730310997319_alter_table_consensus_account_rewards_alter_column_id/up.sql
  indexers/db/migrations/taurus/1730311021220_alter_table_consensus_log_kinds_alter_column_id/down.sql
  indexers/db/migrations/taurus/1730311021220_alter_table_consensus_log_kinds_alter_column_id/up.sql
  indexers/db/package.json
  indexers/gemini-3g/testnet-rewards/.env.develop
  indexers/gemini-3h/consensus/.env.develop
  indexers/gemini-3h/leaderboard/.env.develop
  indexers/gemini-3h/staking/.env.develop
  indexers/package.json
  indexers/taskboard/constants/index.js
  indexers/taskboard/tasks/consensus.js
  indexers/taskboard/tasks/index.js
  indexers/taskboard/utils/db.js
  indexers/taurus/consensus/schema.graphql
  indexers/taurus/consensus/src/mappings/db.ts
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingAccountHandlers.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
  indexers/taurus/consensus/src/mappings/utils.ts
Labels: Review effort [1-5]: 4
