Repository autonomys/astral, pull requests merged in 2024-07, with the labels that each got.

#683 if going to a valid address account route with zero balance, show a z…
  explorer/src/components/Account/Account.tsx
  explorer/src/components/Account/AccountBalancePieChart.tsx
  explorer/src/components/Account/AccountBalanceStats.tsx
  explorer/src/components/Account/AccountDetailsCard.tsx
  explorer/src/components/Account/AccountGraphs.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#678 Apply change unlock operator extrinsic was replaced with unlock nominator
  explorer/src/app/[chain]/layout.tsx
  explorer/src/components/Operator/ActionsDropdown.tsx
  explorer/src/components/Operator/ActionsModal.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorStake.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/PendingTransactions.tsx
  explorer/src/hooks/useTxHelper.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#679 The operators and nominators list in the staking section is very redundant
  explorer/src/components/layout/StakingHeader.tsx
  explorer/src/constants/routes.ts
Labels: enhancement, Review effort [1-5]: 1

#684 Unify <Table> with <NewTable> components — Renamed <SortedTable>
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Account/AccountListCard.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Account/AccountRewardListCard.tsx
  explorer/src/components/Account/AccountRewardTable.tsx
  explorer/src/components/Account/AccountTable.tsx
  explorer/src/components/Block/BlockDetailsEventList.tsx
  explorer/src/components/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Block/BlockDetailsLogList.tsx
  explorer/src/components/Block/BlockDetailsTabs.tsx
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Block/BlockListCard.tsx
  explorer/src/components/Block/BlockTable.tsx
  explorer/src/components/Block/query.ts
  explorer/src/components/Event/EventList.tsx
  explorer/src/components/Event/EventListCard.tsx
  explorer/src/components/Event/EventTable.tsx
  explorer/src/components/Extrinsic/ExtrinsicDetailsEventList.tsx
  explorer/src/components/Extrinsic/ExtrinsicDetailsTab.tsx
  explorer/src/components/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Extrinsic/ExtrinsicListCard.tsx
  explorer/src/components/Extrinsic/ExtrinsicTable.tsx
  explorer/src/components/Home/HomeBlockList.tsx
  explorer/src/components/Home/HomeExtrinsicCard.tsx
  explorer/src/components/Home/HomeExtrinsicList.tsx
  explorer/src/components/Home/index.tsx
  explorer/src/components/Leaderboard/NominatorRewardsList.tsx
  explorer/src/components/Leaderboard/OperatorRewardsList.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardList.tsx
  explorer/src/components/Log/LogDetailsEventList.tsx
  explorer/src/components/Log/LogList.tsx
  explorer/src/components/Log/LogListCard.tsx
  explorer/src/components/Log/LogTable.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorNominatorTable.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/StakeWars/NominatorList.tsx
  explorer/src/components/StakeWars/NominatorListCard.tsx
  explorer/src/components/StakeWars/OperatorListCard.tsx
  explorer/src/components/StakeWars/OperatorsList.tsx
  explorer/src/components/common/SortedTable.tsx
  explorer/src/components/common/Table.tsx
  explorer/src/components/common/TableNavigation.tsx
  explorer/src/components/common/tests/Table.test.tsx
  explorer/src/components/layout/ExtrinsicAndEventResult/index.tsx
  explorer/src/components/layout/SearchResult.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#686 try improving last extrinsics list and pending tx count
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/states/transactions.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#687 improve sanity check
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
Labels: Review effort [1-5]: 2, Bug fix

#668 Add flow to claim operator staking token
  explorer/.env.sample
  explorer/src/app/api/claim/[...params]/route.ts
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/constants/routes.ts
  explorer/src/constants/session.ts
  explorer/src/types/jwt.ts
  explorer/src/utils/auth/providers/discord.ts
  explorer/src/utils/auth/verifyToken.ts
  explorer/src/utils/fauna.ts
  explorer/src/utils/slack.ts
Labels: documentation, enhancement, Review effort [1-5]: 4

#689 Implement Auto-SDK in Astral explorer
  explorer/next.config.js
  explorer/package.json
  explorer/src/app/api/claim/[...params]/route.ts
  explorer/src/components/Operator/ActionsModal.tsx
  explorer/src/components/Operator/OperatorStake.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/yarn.lock
Labels: enhancement, Review effort [1-5]: 4, dependencies

#692 Unify the use of identicon in one component
  explorer/src/components/Account/AccountDetailsCard.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Leaderboard/NominatorRewardsList.tsx
  explorer/src/components/Leaderboard/NominatorRewardsListCard.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardList.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardListCard.tsx
  explorer/src/components/Operator/OperatorDetailsCard.tsx
  explorer/src/components/Operator/OperatorNominatorTable.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/common/AccountIcon.tsx
Labels: enhancement, Review effort [1-5]: 2

#696 Sync prod with main
  explorer/.env.sample
  explorer/next.config.js
  explorer/package.json
  explorer/src/app/api/claim/[...params]/route.ts
  explorer/src/components/Account/AccountDetailsCard.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Leaderboard/NominatorRewardsList.tsx
  explorer/src/components/Leaderboard/NominatorRewardsListCard.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardList.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardListCard.tsx
  explorer/src/components/Operator/ActionsModal.tsx
  explorer/src/components/Operator/OperatorDetailsCard.tsx
  explorer/src/components/Operator/OperatorNominatorTable.tsx
  explorer/src/components/Operator/OperatorStake.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/common/AccountIcon.tsx
  explorer/src/constants/routes.ts
  explorer/src/constants/session.ts
  explorer/src/hooks/useDomainsData.ts
  explorer/src/states/domains.ts
  explorer/src/types/jwt.ts
  explorer/src/utils/auth/providers/discord.ts
  explorer/src/utils/auth/verifyToken.ts
  explorer/src/utils/fauna.ts
  explorer/src/utils/slack.ts
  explorer/yarn.lock
Labels: documentation, enhancement, Review effort [1-5]: 4, tests

#699 re-order chains
  explorer/src/constants/chains.ts
Labels: Review effort [1-5]: 1, Bug fix

#704 fix domain name on Managing page
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#709 stop the wallet sidekick from rendering children components when close
  explorer/src/components/WalletSideKick/index.tsx
Labels: Review effort [1-5]: 1, Bug fix

#710 Sync prod with main
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/WalletSideKick/index.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#708 Only filter out double quote character in keystore
  explorer/src/components/Operator/OperatorStake.tsx
Labels: bug, Review effort [1-5]: 1, Bug fix

#713 Remove fromNow logic on extrinsic and event count cells
  explorer/src/components/Block/BlockList.tsx
Labels: Review effort [1-5]: 1, Bug fix

#717 comment claim mechanism
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
Labels: enhancement, Review effort [1-5]: 2, other

#715 Add out of sync banner
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/common/OutOfSyncBanner.tsx
  explorer/src/components/common/query.ts
  explorer/src/components/layout/Layout.tsx
Labels: enhancement, Review effort [1-5]: 3

#718 Sync prod with main
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Operator/OperatorStake.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/common/OutOfSyncBanner.tsx
  explorer/src/components/common/query.ts
  explorer/src/components/layout/Layout.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#712 add clinic profiler for general squid
  indexers/general-squid/Dockerfile-debug
  indexers/general-squid/docker-compose-debug.yml
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#703 Skip all apollo queries if the window is not in focus
  explorer/gql/oldSquidTypes.ts
  explorer/package.json
  explorer/src/components/Account/Account.tsx
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Account/AccountPreviousRewards.tsx
  explorer/src/components/Account/AccountRewardGraph.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Block/Block.tsx
  explorer/src/components/Block/BlockDetailsEventList.tsx
  explorer/src/components/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Event/Event.tsx
  explorer/src/components/Event/EventList.tsx
  explorer/src/components/Extrinsic/Extrinsic.tsx
  explorer/src/components/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Home/HomeBlockList.tsx
  explorer/src/components/Home/HomeChainInfo.tsx
  explorer/src/components/Home/HomeExtrinsicList.tsx
  explorer/src/components/Home/index.tsx
  explorer/src/components/Leaderboard/NominatorRewardsList.tsx
  explorer/src/components/Leaderboard/OperatorRewardsList.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardList.tsx
  explorer/src/components/Log/Log.tsx
  explorer/src/components/Log/LogList.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/Operator.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/Operator/query.ts
  explorer/src/components/StakeWars/EndGame.tsx
  explorer/src/components/StakeWars/NominatorList.tsx
  explorer/src/components/StakeWars/OperatorsList.tsx
  explorer/src/components/StakeWars/hooks/useStakeWarsData.ts
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/Leaderboard.tsx
  explorer/src/components/WalletSideKick/PendingTransactions.tsx
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/common/Spinner/index.tsx
  explorer/src/components/layout/Footer.tsx
  explorer/src/components/layout/StakingHeader.tsx
  explorer/src/hooks/useSquidQuery.ts
  explorer/src/hooks/useWindowFocus.ts
  explorer/src/states/query.ts
  explorer/yarn.lock
Labels: enhancement, Review effort [1-5]: 3

#720 Fix sorting on nomination tables
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#722 Improve pending transactions
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/PendingTransactions.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/WalletSideKick/query.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3, Bug fix

#724 Improve page count logic
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Block/BlockDetailsEventList.tsx
  explorer/src/components/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Block/BlockDetailsLogList.tsx
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Event/EventList.tsx
  explorer/src/components/Extrinsic/ExtrinsicDetailsEventList.tsx
  explorer/src/components/Extrinsic/ExtrinsicTable.tsx
  explorer/src/components/Leaderboard/NominatorRewardsList.tsx
  explorer/src/components/Leaderboard/OperatorRewardsList.tsx
  explorer/src/components/Leaderboard/VoteBlockRewardList.tsx
  explorer/src/components/Log/LogDetailsEventList.tsx
  explorer/src/components/Log/LogList.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/StakeWars/NominatorList.tsx
  explorer/src/components/StakeWars/OperatorsList.tsx
  explorer/src/components/layout/ExtrinsicAndEventResult/index.tsx
  explorer/src/utils/table.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#728 Fix the account icon next to signing key to show your own op
  explorer/src/components/Operator/OperatorsList.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2, Bug fix

#730 Create a switch in staking section to switch between indexed data and rpc data
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/Operator.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/common/DataSource.tsx
  explorer/src/components/common/DataSourceBanner.tsx
  explorer/src/hooks/useConsensusData.ts
  explorer/src/states/consensus.ts
  explorer/src/states/view.ts
  explorer/src/types/consensus.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix, Error handling

#726 improve the filtering of Actions in Staking section especially for de…
  explorer/src/components/Operator/ActionsDropdown.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/Operator.tsx
  explorer/src/components/Operator/OperatorDetailsCard.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorNominatorTable.tsx
  explorer/src/components/Operator/OperatorsList.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#744 Merge most staking pages together
  explorer/src/app/[chain]/staking/[operatorId]/page.tsx
  explorer/src/app/[chain]/staking/manage/page.tsx
  explorer/src/app/[chain]/staking/nomination/page.tsx
  explorer/src/app/[chain]/staking/nominators/page.tsx
  explorer/src/app/[chain]/staking/page.tsx
  explorer/src/app/[chain]/staking/register/page.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Staking/ActionsDropdown.tsx
  explorer/src/components/Staking/ActionsModal.tsx
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/RegisterOperators.tsx
  explorer/src/components/Staking/query.ts
  explorer/src/components/WalletSideKick/PendingTransactions.tsx
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/common/MyPositionSwitch.tsx
  explorer/src/components/layout/StakingHeader.tsx
  explorer/src/constants/routes.ts
  explorer/src/states/view.ts
Labels: enhancement, Review effort [1-5]: 4, other

#751 improve DB indexing for squid
  indexers/squid-blockexplorer/schema.graphql
Labels: documentation, enhancement, Review effort [1-5]: 3

#749 Improve nonce management for in-app tx
  explorer/src/hooks/useTxHelper.ts
  explorer/src/states/transactions.ts
Labels: enhancement, Review effort [1-5]: 3

#733 Initialize staking squid
  .vscode/astral.code-workspace
  indexers/staking-squid/.dockerignore
  indexers/staking-squid/.env
  indexers/staking-squid/.github/ISSUE_TEMPLATE/bug_report.md
  indexers/staking-squid/.gitignore
  indexers/staking-squid/.npmrc
  indexers/staking-squid/.squidignore
  indexers/staking-squid/LICENSE
  indexers/staking-squid/README.md
  indexers/staking-squid/assets/README.MD
  indexers/staking-squid/commands.json
  indexers/staking-squid/db/migrations/1659350771447-Data.js
  indexers/staking-squid/docker-compose.yml
  indexers/staking-squid/gemini3h.jsonl
  indexers/staking-squid/package-lock.json
  indexers/staking-squid/package.json
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/scripts/docker-run.sh
  indexers/staking-squid/scripts/sub-client.js
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/main.ts
  indexers/staking-squid/src/model/generated/account.model.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/model/generated/marshal.ts
  indexers/staking-squid/src/model/generated/transfer.model.ts
  indexers/staking-squid/src/model/index.ts
  indexers/staking-squid/src/processor.ts
  indexers/staking-squid/src/types/calls.ts
  indexers/staking-squid/src/types/constants.ts
  indexers/staking-squid/src/types/domains/calls.ts
  indexers/staking-squid/src/types/domains/constants.ts
  indexers/staking-squid/src/types/domains/events.ts
  indexers/staking-squid/src/types/domains/storage.ts
  indexers/staking-squid/src/types/events.ts
  indexers/staking-squid/src/types/index.ts
  indexers/staking-squid/src/types/storage.ts
  indexers/staking-squid/src/types/support.ts
  indexers/staking-squid/src/types/v0.ts
  indexers/staking-squid/src/types/v1.ts
  indexers/staking-squid/src/types/v3.ts
  indexers/staking-squid/tsconfig.json
  indexers/staking-squid/typegen.json
Labels: documentation, enhancement, Review effort [1-5]: 5, indexer

#745 Add RPC data source for operator detail
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/query.ts
  explorer/src/hooks/useConsensusData.ts
  explorer/src/states/consensus.ts
  explorer/src/states/query.ts
  explorer/src/types/consensus.ts
  explorer/src/utils/number.ts
  explorer/src/utils/operator.ts
  explorer/src/utils/string.ts
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#746 Add rpc data source for nominators management
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/hooks/useConsensusData.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#755 Add the amount pending next to each nominator when on rpc
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/hooks/useConsensusData.ts
  explorer/src/utils/chainStateParsing.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#756 Display withdrawals on staking when on rpc
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/constants/general.ts
  explorer/src/states/consensus.ts
  explorer/src/states/domains.ts
  explorer/src/states/transactions.ts
  explorer/src/states/view.ts
  explorer/src/types/consensus.ts
  explorer/src/utils/chainStateParsing.ts
  explorer/src/utils/number.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#757 Add operators in staking squid
  indexers/staking-squid/.env
  indexers/staking-squid/.github/ISSUE_TEMPLATE/bug_report.md
  indexers/staking-squid/.gitignore
  indexers/staking-squid/assets/README.MD
  indexers/staking-squid/commands.json
  indexers/staking-squid/db/migrations/1659350771447-Data.js
  indexers/staking-squid/db/migrations/1721651870023-Data.js
  indexers/staking-squid/gemini3h.jsonl
  indexers/staking-squid/package-lock.json
  indexers/staking-squid/package.json
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/blocks/index.ts
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/events/domain.ts
  indexers/staking-squid/src/events/epoch.ts
  indexers/staking-squid/src/events/index.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/extrinsics/index.ts
  indexers/staking-squid/src/extrinsics/operator.ts
  indexers/staking-squid/src/main.ts
  indexers/staking-squid/src/model/generated/account.model.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/model/generated/transfer.model.ts
  indexers/staking-squid/src/processor.ts
  indexers/staking-squid/src/storage/domain.ts
  indexers/staking-squid/src/storage/index.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/types/domains/calls.ts
  indexers/staking-squid/src/types/domains/events.ts
  indexers/staking-squid/src/types/domains/storage.ts
  indexers/staking-squid/src/types/index.ts
  indexers/staking-squid/src/types/v5.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 5, Bug fix, tests, indexer

#758 Sync prod with main
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/query.ts
  explorer/src/constants/general.ts
  explorer/src/hooks/useConsensusData.ts
  explorer/src/states/consensus.ts
  explorer/src/states/domains.ts
  explorer/src/states/query.ts
  explorer/src/states/transactions.ts
  explorer/src/states/view.ts
  explorer/src/types/consensus.ts
  explorer/src/utils/chainStateParsing.ts
  explorer/src/utils/number.ts
  explorer/src/utils/operator.ts
  explorer/src/utils/string.ts
  indexers/staking-squid/.env
  indexers/staking-squid/.github/ISSUE_TEMPLATE/bug_report.md
  indexers/staking-squid/.gitignore
  indexers/staking-squid/assets/README.MD
  indexers/staking-squid/commands.json
  indexers/staking-squid/db/migrations/1659350771447-Data.js
  indexers/staking-squid/db/migrations/1721651870023-Data.js
  indexers/staking-squid/gemini3h.jsonl
  indexers/staking-squid/package-lock.json
  indexers/staking-squid/package.json
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/blocks/index.ts
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/events/domain.ts
  indexers/staking-squid/src/events/epoch.ts
  indexers/staking-squid/src/events/index.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/extrinsics/index.ts
  indexers/staking-squid/src/extrinsics/operator.ts
  indexers/staking-squid/src/main.ts
  indexers/staking-squid/src/model/generated/account.model.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/model/generated/transfer.model.ts
  indexers/staking-squid/src/processor.ts
  indexers/staking-squid/src/storage/domain.ts
  indexers/staking-squid/src/storage/index.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/types/domains/calls.ts
  indexers/staking-squid/src/types/domains/events.ts
  indexers/staking-squid/src/types/domains/storage.ts
  indexers/staking-squid/src/types/index.ts
  indexers/staking-squid/src/types/v5.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix, tests

#764 Update link and add academy link
  explorer/src/components/layout/Footer.tsx
  explorer/src/constants/routes.ts
Labels: enhancement, Review effort [1-5]: 2

#766 Improve staking squid
  indexers/staking-squid/db/migrations/1721778314620-Data.js
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/events/index.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/storage/deposit.ts
  indexers/staking-squid/src/storage/domain.ts
  indexers/staking-squid/src/storage/index.ts
  indexers/staking-squid/src/storage/nominator.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/storage/withdrawal.ts
Labels: enhancement, Review effort [1-5]: 4, other

#759 Improve address book
  explorer/src/components/WalletSideKick/AccountPreferencesModal.tsx
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/constants/wallet.ts
  explorer/src/states/addressBook.ts
  explorer/src/types/wallet.ts
Labels: enhancement, Review effort [1-5]: 4, other

#760 Add dev mode to wallet sidekick
  explorer/src/components/WalletSideKick/AccountHeader.tsx
  explorer/src/components/WalletSideKick/AccountPreferencesModal.tsx
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/constants/wallet.ts
  explorer/src/states/preferences.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#765 Improve withdrawals flow
  explorer/src/components/Staking/ActionsDropdown.tsx
  explorer/src/components/Staking/MyWithdrawals.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/types/consensus.ts
  explorer/src/utils/chainStateParsing.ts
Labels: enhancement, Review effort [1-5]: 4

#769 replace subspace for autonomys github org
  .github/workflows/gh-deploy-micro-squids.yml
  README.md
  docker-compose-all-squids.yml
  explorer/README.md
  explorer/src/constants/routes.ts
  health-check/README.md
  indexers/account-squid/scripts/install-sqd.sh
  indexers/general-squid/scripts/install-sqd.sh
  indexers/rewards-squid/scripts/install-sqd.sh
  indexers/squid-blockexplorer/README.md
  indexers/squid-blockexplorer/devnet/docker-compose.yml
  indexers/staking-squid/package.json
Labels: documentation, enhancement, Review effort [1-5]: 2

#770 Update to auto sdk 0.1.8
  explorer/package.json
  explorer/src/app/api/claim/[...params]/route.ts
  explorer/src/components/Staking/RegisterOperators.tsx
  explorer/src/components/WalletSideKick/AccountPreferencesModal.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/WalletSideKick/ExtrinsicsLab.tsx
  explorer/src/hooks/useSearch.ts
  explorer/src/hooks/useTxHelper.ts
  explorer/src/providers/WalletProvider.tsx
  explorer/src/states/consensus.ts
  explorer/src/types/consensus.ts
  explorer/src/utils/auth/providers/subspace.ts
  explorer/src/utils/chainStateParsing.ts
  explorer/src/utils/formatAddress.ts
  explorer/yarn.lock
Labels: enhancement, dependencies

#777 fix account reward page
  explorer/src/components/Account/AccountRewardList.tsx
Labels: Review effort [1-5]: 2, Bug fix

#778 Fix query on nova blocks list
  explorer/gql/oldSquidTypes.ts
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Block/query.ts
Labels: Review effort [1-5]: 2, Bug fix

#776 Update Subspace -> Autonomys links
  explorer/src/components/layout/Footer.tsx
  explorer/src/constants/routes.ts
Labels: enhancement, Review effort [1-5]: 2

#780 fix route following s addition
  explorer/src/app/[chain]/domains/layout.tsx
  explorer/src/app/[chain]/domains/page.tsx
Labels: Review effort [1-5]: 2, Bug fix

#781 Fix full export for Acount extrinsics list and account rewards list
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountRewardList.tsx
Labels: Review effort [1-5]: 2, Bug fix

#782 Allow visitors to use RPC data
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/providers/WalletProvider.tsx
Labels: enhancement, Review effort [1-5]: 2

#783 We always miss the last page if the total % pageSize > 0
  explorer/src/utils/table.ts
Labels: Review effort [1-5]: 1, Bug fix

#784 Sync Production with main
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/providers/WalletProvider.tsx
  explorer/src/utils/table.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix
