Repository autonomys/astral, pull requests merged in 2024-03, with the labels that each got.

#543 Fix operator status for3h
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/utils/operator.ts
  explorer/src/utils/string.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#551 add netlify CI/CD for production deployment
  .github/workflows/gh-deploy-production.yml
Labels: enhancement, Review effort [1-5]: 2

#552 fix(generalSquid): issue with deployment image ver 2
  general-squid/.gitignore
  general-squid/package.json
  rewards-squid/.gitignore
Labels: enhancement, Review effort [1-5]: 2

#553 fix(account): show extrinsics in account page
  client/src/Account/components/AccountExtrinsicList.tsx
Labels: Review effort [1-5]: 1, bug_fix

#555 fix(dockerfile): update correct node version
  account-squid/Dockerfile
  general-squid/Dockerfile
  rewards-squid/Dockerfile
Labels: enhancement, Review effort [1-5]: 2

#559 fix(accountSquid): fix issue when call doesn't have defined account s…
  account-squid/.gitignore
  account-squid/src/account/utils.ts
  account-squid/src/main.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix
