Repository autonomys/astral, pull requests merged in 2024-11, with the labels that each got.

#900 changes to docker stack env vars and caddy
  .env
  docker-compose.yml
  indexers/Caddyfile
Labels: Review effort [1-5]: 2

#901 fix postgres path for indexer
  docker-compose.prod.yml
Labels: Review effort [1-5]: 1

#902 Docker tag no default value and add missing .env.prod and .env.dev
  .env
  .env.dev
  .env.prod
  docker-compose.yml
  indexers/package.json
Labels: Review effort [1-5]: 2

#903 Prevent indexing too close to the head of the chain
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 3

#906 Disable leaderboard
  explorer/gql/graphql.ts
  explorer/src/app/[chain]/leaderboard/accounts/page.tsx
  explorer/src/app/[chain]/leaderboard/farmers/page.tsx
  explorer/src/app/[chain]/leaderboard/nominators/page.tsx
  explorer/src/app/[chain]/leaderboard/operators/page.tsx
  explorer/src/app/[chain]/leaderboard/page.tsx
  explorer/src/constants/routes.ts
Labels: Review effort [1-5]: 2

#905 Improve chain offset logic
  indexers/taurus/consensus/src/mappings/helper.ts
Labels: Review effort [1-5]: 2

#914 Change ss58 prefix and token symbol
  explorer/src/constants/general.ts
Labels: Review effort [1-5]: 1

#913 Fix timestamp to local time
  explorer/src/app/[chain]/consensus/accounts/[accountId]/image/route.tsx
  explorer/src/app/[chain]/image/route.tsx
  explorer/src/components/Consensus/Account/AccountExtrinsicList.tsx
  explorer/src/components/Consensus/Account/AccountGraphs.tsx
  explorer/src/components/Consensus/Account/AccountLatestRewards.tsx
  explorer/src/components/Consensus/Account/AccountPreviousRewards.tsx
  explorer/src/components/Consensus/Account/AccountRewardList.tsx
  explorer/src/components/Consensus/Account/AccountRewardsHistory.tsx
  explorer/src/components/Consensus/Account/AccountTransfersList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsCard.tsx
  explorer/src/components/Consensus/Block/BlockDetailsEventList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsLogList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsTabs.tsx
  explorer/src/components/Consensus/Block/BlockList.tsx
  explorer/src/components/Consensus/Event/EventDetailsCard.tsx
  explorer/src/components/Consensus/Event/EventList.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsCard.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsEventList.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Consensus/Home/HomeBlockList.tsx
  explorer/src/components/Consensus/Home/HomeExtrinsicList.tsx
  explorer/src/components/Consensus/Log/LogDetailsCard.tsx
  explorer/src/components/Consensus/Log/LogDetailsEventList.tsx
  explorer/src/components/Domain/DomainDetailsCard.tsx
  explorer/src/components/Leaderboard/LeaderboardList.tsx
  explorer/src/components/Staking/NominationsTable.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/common/PageTabs.tsx
  explorer/src/components/layout/Footer.tsx
  explorer/src/components/layout/MobileHeader.tsx
  explorer/src/utils/time.ts
Labels: Review effort [1-5]: 3

#912 Gate send token for testnet only
  explorer/src/components/WalletSideKick/ActionsButtons.tsx
Labels: Review effort [1-5]: 2

#915 Improve token symbol for multiple chain
  explorer/src/app/[chain]/consensus/accounts/[accountId]/image/route.tsx
  explorer/src/app/[chain]/testnet-rewards/page.tsx
  explorer/src/components/Consensus/Account/AccountBalanceStats.tsx
  explorer/src/components/Consensus/Account/AccountGraphTabs.tsx
  explorer/src/components/Consensus/Account/AccountLatestRewards.tsx
  explorer/src/components/Consensus/Account/AccountPreviousRewards.tsx
  explorer/src/components/Consensus/Account/AccountRewardGraph.tsx
  explorer/src/components/Consensus/Account/AccountRewardList.tsx
  explorer/src/components/Consensus/Account/AccountTransfersList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsCard.tsx
  explorer/src/components/Consensus/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Consensus/Block/BlockList.tsx
  explorer/src/components/Consensus/Event/EventDetailsCard.tsx
  explorer/src/components/Consensus/Event/EventList.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsCard.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Consensus/Home/HomeExtrinsicList.tsx
  explorer/src/components/Domain/DomainDetailsCard.tsx
  explorer/src/components/Domain/DomainsList.tsx
  explorer/src/components/Leaderboard/LeaderboardList.tsx
  explorer/src/components/Leaderboard/index.tsx
  explorer/src/components/Staking/ActionsModal.tsx
  explorer/src/components/Staking/MyWithdrawals.tsx
  explorer/src/components/Staking/NominationsTable.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/RegisterOperators.tsx
  explorer/src/components/TestnetRewards/RewardHistory.tsx
  explorer/src/components/WalletSideKick/Actions/ClaimStakingToken.tsx
  explorer/src/components/WalletSideKick/ActionsButtons.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/layout/Footer.tsx
  explorer/src/components/layout/MobileHeader.tsx
  explorer/src/constants/general.ts
  explorer/src/providers/ChainProvider.tsx
  explorer/src/utils/network.ts
  explorer/src/utils/slack.ts
Labels: Review effort [1-5]: 3

#917 Handle route without network
  explorer/src/middleware.ts
Labels: Review effort [1-5]: 2

#923 Add support for su address prefix in testnet rewards
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
  explorer/src/constants/general.ts
  explorer/src/utils/formatAddress.ts
Labels: Review effort [1-5]: 3

#925 Expose hasura endpoint and subql health endpoint
  indexers/Caddyfile
Labels: Review effort [1-5]: 4

#926 ci workflow deploy on subql host
  .github/workflows/gh-deploy-monolith-squid.yml
  .github/workflows/gh-deploy-subql.yml
Labels: Review effort [1-5]: 3

#927 caddy auth and security
  indexers/Caddyfile
Labels: Review effort [1-5]: 2

#928 auth and fix hasura proxy
  docker-compose.yml
  indexers/Caddyfile
Labels: Review effort [1-5]: 2

#921 Add mainnet to explorer fe
  explorer/.env.sample
  explorer/package.json
  explorer/src/components/Consensus/Home/HomeCards.tsx
  explorer/src/constants/indexers.ts
  explorer/yarn.lock
Labels: Review effort [1-5]: 2

#933 Add Hasura action to update account balance
  docker-compose.yml
  indexers/db/metadata/actions.graphql
  indexers/db/metadata/actions.yaml
  indexers/taskboard/Dockerfile
  indexers/taskboard/constants/index.js
  indexers/taskboard/index.js
  indexers/taskboard/package.json
  indexers/taskboard/tasks/index.js
  indexers/taskboard/tasks/updateAccount.js
  indexers/taskboard/utils/db.js
Labels: Review effort [1-5]: 4

#934 Improve taskboard setup
  .env
  .vscode/astral.code-workspace
  docker-compose.yml
  indexers/db/metadata/actions.graphql
  indexers/db/metadata/actions.yaml
  indexers/taskboard/Dockerfile
  indexers/taskboard/index.js
  indexers/taskboard/package.json
  indexers/taskboard/src/constants/index.ts
  indexers/taskboard/src/index.ts
  indexers/taskboard/src/tasks/consensus.ts
  indexers/taskboard/src/tasks/index.ts
  indexers/taskboard/src/tasks/leaderboardSortAndRank.ts
  indexers/taskboard/src/tasks/slackNotification.ts
  indexers/taskboard/src/tasks/updateAccount.ts
  indexers/taskboard/src/types/ejs.d.ts
  indexers/taskboard/src/utils/bull.ts
  indexers/taskboard/src/utils/db.ts
  indexers/taskboard/src/utils/helper.ts
  indexers/taskboard/src/utils/slack.ts
  indexers/taskboard/src/utils/store.ts
  indexers/taskboard/src/views/index.ejs
  indexers/taskboard/src/views/login.ejs
  indexers/taskboard/tasks/index.js
  indexers/taskboard/tsconfig.json
  indexers/taskboard/utils/db.js
  indexers/yarn.lock
Labels: Review effort [1-5]: 3

#931 Fix events-extrinsics relation in hasura metadata
  indexers/db/metadata/databases/default/tables/consensus_events.yaml
  indexers/db/metadata/databases/default/tables/consensus_extrinsics.yaml
Labels: Review effort [1-5]: 2

#932 Seed dictionary and consensus schema at postgres init
  docker-compose.yml
  indexers/db/docker-entrypoint-initdb.d/init-db.sql
  indexers/db/migrations/default/1730310914662_alter_table_consensus_sections_alter_column_id/down.sql
  indexers/db/migrations/default/1730310914662_alter_table_consensus_sections_alter_column_id/up.sql
  indexers/db/migrations/default/1730310946777_alter_table_consensus_event_modules_alter_column_id/down.sql
  indexers/db/migrations/default/1730310946777_alter_table_consensus_event_modules_alter_column_id/up.sql
  indexers/db/migrations/default/1730310960555_alter_table_consensus_extrinsic_modules_alter_column_id/down.sql
  indexers/db/migrations/default/1730310960555_alter_table_consensus_extrinsic_modules_alter_column_id/up.sql
  indexers/db/migrations/default/1730310972982_alter_table_consensus_accounts_alter_column_id/down.sql
  indexers/db/migrations/default/1730310972982_alter_table_consensus_accounts_alter_column_id/up.sql
  indexers/db/migrations/default/1730310983740_alter_table_consensus_account_profiles_alter_column_id/down.sql
  indexers/db/migrations/default/1730310983740_alter_table_consensus_account_profiles_alter_column_id/up.sql
  indexers/db/migrations/default/1730310997319_alter_table_consensus_account_rewards_alter_column_id/down.sql
  indexers/db/migrations/default/1730310997319_alter_table_consensus_account_rewards_alter_column_id/up.sql
  indexers/db/migrations/default/1730311021220_alter_table_consensus_log_kinds_alter_column_id/down.sql
  indexers/db/migrations/default/1730311021220_alter_table_consensus_log_kinds_alter_column_id/up.sql
  indexers/mainnet/consensus/schema.graphql
  indexers/taurus/consensus/schema.graphql
Labels: Review effort [1-5]: 4

#937 Remove platform tag for node
  docker-compose.yml
Labels: Review effort [1-5]: 1

#939 Remove pot external entropy to not cause issue on taurus/mainnet
  docker-compose.yml
Labels: Review effort [1-5]: 1

#940 fix ports for indexer services
  docker-compose.yml
Labels: Review effort [1-5]: 1

#941 Improve docker setup for node
  .env
  docker-compose.yml
Labels: Review effort [1-5]: 2

#944 Change to use PB rather than PiB
  explorer/gql/graphql.ts
  explorer/src/app/[chain]/image/route.tsx
  explorer/src/components/Consensus/Home/HomeChainInfo.tsx
  explorer/src/utils/number.ts
Labels: Review effort [1-5]: 2

#946 Fix ports collision
  .env
  docker-compose.yml
  indexers/mainnet/consensus/project.ts
  indexers/taurus/consensus/project.ts
Labels: Review effort [1-5]: 3

#942 add node logging
  docker-compose.prod.yml
  docker-compose.yml
Labels: Review effort [1-5]: 2

#949 Improve consensus tasks to be independent from indexer
  indexers/mainnet/consensus/src/mappings/helper.ts
  indexers/mainnet/consensus/src/mappings/mappingHandlers.ts
  indexers/taskboard/src/index.ts
  indexers/taskboard/src/tasks/consensus.ts
  indexers/taskboard/src/tasks/index.ts
  indexers/taskboard/src/utils/cron.ts
  indexers/taskboard/src/utils/store.ts
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 3

#950 Improve leaderboard indexers and tasks similarly
  docker-compose.yml
  indexers/mainnet/leaderboard/project.ts
  indexers/mainnet/leaderboard/src/mappings/helper.ts
  indexers/mainnet/leaderboard/src/mappings/mappingHandlers.ts
  indexers/taskboard/src/tasks/consensus.ts
  indexers/taskboard/src/tasks/index.ts
  indexers/taskboard/src/tasks/leaderboardSortAndRank.ts
  indexers/taurus/leaderboard/project.ts
  indexers/taurus/leaderboard/src/mappings/helper.ts
  indexers/taurus/leaderboard/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 3

#951 Improve Postgres init with leaderboard historical tables
  indexers/db/docker-entrypoint-initdb.d/init-db.sql
Labels: Review effort [1-5]: 4

#952 Change subscan url
  .vscode/astral.code-workspace
  .vscode/settings.json
  explorer/src/components/common/IndexingError.tsx
  explorer/src/components/common/OutOfSyncBanner.tsx
  explorer/src/constants/routes.ts
Labels: Review effort [1-5]: 2

#936 Move most of the testnet rewards logic to a reusable file and reuse it for account previous rewards
  explorer/src/components/Consensus/Account/AccountPreviousRewards.tsx
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
  explorer/src/utils/testnetRewards.ts
Labels: Review effort [1-5]: 4

#957 Add account balance history
  explorer/gql/graphql.ts
  explorer/src/components/Consensus/Account/Account.tsx
  explorer/src/components/Consensus/Account/BalanceHistory.tsx
  explorer/src/components/Consensus/Account/query.ts
  indexers/db/metadata/databases/default/tables/consensus_account_histories.yaml
Labels: Review effort [1-5]: 3

#958 Homepage search all return a 404 page when searching with an accountid
  explorer/gql/graphql.ts
  explorer/src/components/Consensus/Block/Block.tsx
  explorer/src/components/Consensus/Block/query.ts
  explorer/src/components/Consensus/Extrinsic/query.ts
  explorer/src/components/common/queries/index.ts
  explorer/src/constants/general.ts
  explorer/src/constants/routes.ts
  explorer/src/hooks/useSearch.ts
Labels: Review effort [1-5]: 4

#960 Update explorer to auto sdk 1.0.7 and add binary space formatting via tooltip
  explorer/gql/graphql.ts
  explorer/package.json
  explorer/src/app/[chain]/image/route.tsx
  explorer/src/components/Consensus/Home/HomeCards.tsx
  explorer/src/components/Consensus/Home/HomeChainInfo.tsx
  explorer/src/components/Consensus/Home/HomeInfoCard.tsx
  explorer/src/components/Consensus/Home/query.ts
  explorer/src/utils/number.ts
  explorer/yarn.lock
Labels: Review effort [1-5]: 3

#961 Sync production branch w/ main
  explorer/gql/graphql.ts
  explorer/package.json
  explorer/src/app/[chain]/image/route.tsx
  explorer/src/components/Consensus/Account/Account.tsx
  explorer/src/components/Consensus/Account/AccountPreviousRewards.tsx
  explorer/src/components/Consensus/Account/BalanceHistory.tsx
  explorer/src/components/Consensus/Account/query.ts
  explorer/src/components/Consensus/Block/Block.tsx
  explorer/src/components/Consensus/Block/query.ts
  explorer/src/components/Consensus/Extrinsic/query.ts
  explorer/src/components/Consensus/Home/HomeCards.tsx
  explorer/src/components/Consensus/Home/HomeChainInfo.tsx
  explorer/src/components/Consensus/Home/HomeInfoCard.tsx
  explorer/src/components/Consensus/Home/query.ts
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
  explorer/src/components/common/queries/index.ts
  explorer/src/constants/general.ts
  explorer/src/constants/routes.ts
  explorer/src/hooks/useSearch.ts
  explorer/src/utils/number.ts
  explorer/src/utils/testnetRewards.ts
  explorer/yarn.lock
  indexers/db/metadata/databases/default/tables/consensus_account_histories.yaml
Labels: Review effort [1-5]: 4

#965 Replace old token symbol by chain specific token symbol or auto-sdk testnet constant
  explorer/src/components/Consensus/Account/AccountList.tsx
  explorer/src/components/TestnetRewards/TestnetRewardsTable.tsx
Labels: Review effort [1-5]: 2

#966 Remove consensus indexer offset logic
  indexers/mainnet/consensus/src/mappings/helper.ts
  indexers/mainnet/consensus/src/mappings/mappingAccountHandlers.ts
  indexers/mainnet/consensus/src/mappings/mappingHandlers.ts
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingAccountHandlers.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 3

#967 Enable and fix leaderboard in explorer
  explorer/src/app/[chain]/leaderboard/accounts/page.tsx
  explorer/src/app/[chain]/leaderboard/farmers/page.tsx
  explorer/src/app/[chain]/leaderboard/nominators/page.tsx
  explorer/src/app/[chain]/leaderboard/operators/page.tsx
  explorer/src/app/[chain]/leaderboard/page.tsx
  explorer/src/components/Leaderboard/index.tsx
  explorer/src/constants/routes.ts
Labels: Review effort [1-5]: 2

#974 Improve precision under 1 minute
  explorer/src/utils/time.ts
Labels: Review effort [1-5]: 2

#973 Fix mobile menu footer
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/common/ErrorFallback/index.tsx
  explorer/src/components/layout/Footer.tsx
  explorer/src/components/layout/MobileHeader.tsx
  explorer/src/constants/metadata.ts
  explorer/src/constants/routes.ts
Labels: Review effort [1-5]: 2

#975 Few leaderboard fixes
  explorer/gql/graphql.ts
  explorer/src/components/Leaderboard/LeaderboardList.tsx
  explorer/src/components/Leaderboard/index.tsx
  explorer/src/components/Leaderboard/query.ts
  explorer/src/components/common/AccountIcon.tsx
  explorer/src/components/common/TableSettings.tsx
  explorer/src/constants/tables.ts
Labels: Review effort [1-5]: 3

#978 Use block hash instead of extrinsic hash in extrinsic table for extrinsic hash
  indexers/mainnet/consensus/src/mappings/mappingHandlers.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
Labels: Review effort [1-5]: 2, Bug fix

#976 Consensus indexer converts data to CID
  .github/workflows/build.yaml
  indexers/db/docker-entrypoint-initdb.d/init-db.sql
  indexers/mainnet/consensus/package.json
  indexers/mainnet/consensus/schema.graphql
  indexers/mainnet/consensus/src/mappings/db.ts
  indexers/mainnet/consensus/src/mappings/helper.ts
  indexers/mainnet/consensus/src/mappings/mappingHandlers.ts
  indexers/mainnet/consensus/src/mappings/types.ts
  indexers/mainnet/consensus/src/mappings/utils.ts
  indexers/taurus/consensus/package.json
  indexers/taurus/consensus/schema.graphql
  indexers/taurus/consensus/src/mappings/db.ts
  indexers/taurus/consensus/src/mappings/helper.ts
  indexers/taurus/consensus/src/mappings/mappingHandlers.ts
  indexers/taurus/consensus/src/mappings/types.ts
  indexers/taurus/consensus/src/mappings/utils.ts
Labels: Review effort [1-5]: 4

#977 Add files indexers
  docker-compose.yml
  indexers/db/metadata/databases/default/tables/files_chunks.yaml
  indexers/db/metadata/databases/default/tables/files_cids.yaml
  indexers/db/metadata/databases/default/tables/files_file_cids.yaml
  indexers/db/metadata/databases/default/tables/files_files.yaml
  indexers/db/metadata/databases/default/tables/files_folder_cids.yaml
  indexers/db/metadata/databases/default/tables/files_folders.yaml
  indexers/db/metadata/databases/default/tables/files_metadata.yaml
  indexers/db/metadata/databases/default/tables/files_metadata_cids.yaml
  indexers/db/metadata/databases/default/tables/tables.yaml
  indexers/mainnet/files/.gitignore
  indexers/mainnet/files/LICENSE
  indexers/mainnet/files/README.md
  indexers/mainnet/files/package.json
  indexers/mainnet/files/project.ts
  indexers/mainnet/files/schema.graphql
  indexers/mainnet/files/src/index.ts
  indexers/mainnet/files/src/mappings/db.ts
  indexers/mainnet/files/src/mappings/mappingHandlers.ts
  indexers/mainnet/files/src/mappings/types.ts
  indexers/mainnet/files/tsconfig.json
  indexers/taurus/files/.gitignore
  indexers/taurus/files/LICENSE
  indexers/taurus/files/README.md
  indexers/taurus/files/package.json
  indexers/taurus/files/project.ts
  indexers/taurus/files/schema.graphql
  indexers/taurus/files/src/index.ts
  indexers/taurus/files/src/mappings/db.ts
  indexers/taurus/files/src/mappings/mappingHandlers.ts
  indexers/taurus/files/src/mappings/types.ts
  indexers/taurus/files/tsconfig.json
  indexers/yarn.lock
Labels: Review effort [1-5]: 4

#983 Improve db config
  docker-compose.yml
  indexers/db/postgresql.conf
  indexers/taskboard/src/tasks/consensus.ts
  indexers/taskboard/src/tasks/leaderboardSortAndRank.ts
Labels: Review effort [1-5]: 3

#986 Imove config to metadata since these env are deprecated
  docker-compose.yml
  indexers/db/metadata/databases/databases.yaml
Labels: Review effort [1-5]: 2

#987 Use consensus account histories for account detail page
  explorer/gql/graphql.ts
  explorer/src/app/[chain]/consensus/accounts/[accountId]/image/route.tsx
  explorer/src/components/Consensus/Account/Account.tsx
  explorer/src/components/Consensus/Account/AccountBalancePieChart.tsx
  explorer/src/components/Consensus/Account/AccountBalanceStats.tsx
  explorer/src/components/Consensus/Account/AccountDetailsCard.tsx
  explorer/src/components/Consensus/Account/AccountGraphs.tsx
  explorer/src/components/Consensus/Account/AccountRewardList.tsx
  explorer/src/components/Consensus/Account/query.ts
Labels: Review effort [1-5]: 3

#984 Add subql patch script
  indexers/patch.sh
Labels: Review effort [1-5]: 2

#992 Fix details page sub-list, improve sorting and caching
  explorer/gql/graphql.ts
  explorer/src/components/Consensus/Account/Account.tsx
  explorer/src/components/Consensus/Account/AccountExtrinsicList.tsx
  explorer/src/components/Consensus/Account/AccountList.tsx
  explorer/src/components/Consensus/Account/AccountRewardGraph.tsx
  explorer/src/components/Consensus/Account/AccountRewardList.tsx
  explorer/src/components/Consensus/Account/AccountTransfersList.tsx
  explorer/src/components/Consensus/Account/BalanceHistory.tsx
  explorer/src/components/Consensus/Account/query.ts
  explorer/src/components/Consensus/Block/Block.tsx
  explorer/src/components/Consensus/Block/BlockDetailsEventList.tsx
  explorer/src/components/Consensus/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Consensus/Block/BlockList.tsx
  explorer/src/components/Consensus/Block/query.ts
  explorer/src/components/Consensus/Event/Event.tsx
  explorer/src/components/Consensus/Event/EventList.tsx
  explorer/src/components/Consensus/Extrinsic/Extrinsic.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsEventList.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicDetailsTab.tsx
  explorer/src/components/Consensus/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Consensus/Extrinsic/query.ts
  explorer/src/components/Consensus/Home/index.tsx
  explorer/src/components/Consensus/Log/Log.tsx
  explorer/src/components/Consensus/Log/LogList.tsx
  explorer/src/components/Domain/Domain.tsx
  explorer/src/components/Domain/DomainsList.tsx
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/WalletSideKick/Actions/ClaimStakingToken.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/Leaderboard.tsx
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/common/ErrorFallback/index.tsx
  explorer/src/hooks/useIndexersQuery.ts
  explorer/src/states/query.ts
  explorer/src/utils/sort.ts
Labels: Review effort [1-5]: 4

#990 Improve consensus task to run query in parallel and only check a specific range
  indexers/taskboard/src/tasks/consensus.ts
  indexers/taskboard/src/utils/db.ts
Labels: Review effort [1-5]: 3
