Repository autonomys/astral, pull requests merged in 2024-04, with the labels that each got.

#561 fix(accountSquid): double encoding
  account-squid/src/account/utils.ts
Labels: Review effort [1-5]: 1, bug_fix

#564 Fix(rewardsSquid): add missing entities and status to nominator
  rewards-squid/db/migrations/1712574163299-Data.js
  rewards-squid/schema.graphql
  rewards-squid/src/blocks/utils.ts
  rewards-squid/src/main.ts
  rewards-squid/src/model/generated/account.model.ts
  rewards-squid/src/model/generated/deposit.model.ts
  rewards-squid/src/model/generated/index.ts
  rewards-squid/src/model/generated/nominator.model.ts
  rewards-squid/src/model/generated/operator.model.ts
  rewards-squid/src/model/generated/operatorUnlockedFunds.model.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#566 Fix/types rewards squid
  rewards-squid/db/migrations/1713160183202-Data.js
  rewards-squid/gemini3h.jsonl
  rewards-squid/schema.graphql
  rewards-squid/src/blocks/utils.ts
  rewards-squid/src/main.ts
  rewards-squid/src/model/generated/account.model.ts
  rewards-squid/src/model/generated/deposit.model.ts
  rewards-squid/src/model/generated/index.ts
  rewards-squid/src/model/generated/nominator.model.ts
  rewards-squid/src/model/generated/operator.model.ts
  rewards-squid/src/model/generated/operatorUnlockedFunds.model.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#567 fix(rewards-squid): resolve issue with types on rewards squid
  rewards-squid/db/migrations/1713160183202-Data.js
  rewards-squid/gemini3h.jsonl
  rewards-squid/schema.graphql
  rewards-squid/src/blocks/utils.ts
  rewards-squid/src/model/generated/deposit.model.ts
  rewards-squid/src/model/generated/operatorUnlockedFunds.model.ts
Labels: enhancement, Review effort [1-5]: 2

#568 fix(AccountRewards): Account rewards was giving 404
  explorer/src/app/[chain]/consensus/accounts/[accountId]/rewards/page.tsx
  explorer/src/components/Account/AccountRewardList.tsx
Labels: enhancement, Review effort [1-5]: 3

#569 fix(extrinsic): issue when loading extrisinc by id page
  explorer/src/components/Extrinsic/Extrinsic.tsx
  explorer/src/components/Operator/NominationManagement.tsx
Labels: bug_fix, Review effort [1-5]: 2

#571 Wallet sidekick staking summary not accurate
  explorer/gql/gql.ts
  explorer/gql/graphql.ts
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/WalletSideKick/query.ts
Labels: bug, enhancement, bug_fix, Review effort [1-5]: 3

#573 Improve Readme
  README.md
  explorer/README.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#572 Add UnlockFunds and UnlockOperator actions
  explorer/gql/gql.ts
  explorer/gql/graphql.ts
  explorer/src/components/Operator/ActionsDropdown.tsx
  explorer/src/components/Operator/ActionsModal.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/Operator/OperatorsListCard.tsx
  explorer/src/components/Operator/query.ts
  explorer/src/utils/operator.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#575 Add next-auth to verify user wallet ownership and discord account and give roles
  .vscode/astral.code-workspace
  .vscode/settings.json
  explorer/.env.sample
  explorer/.gitignore
  explorer/gql/gql.ts
  explorer/gql/graphql.ts
  explorer/next-auth.d.ts
  explorer/package.json
  explorer/src/app/api/auth/[...nextauth]/route.ts
  explorer/src/components/Home/index.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/WalletSideKick/query.ts
  explorer/src/components/icons/CheckMarkIcon.tsx
  explorer/src/components/icons/index.ts
  explorer/src/components/layout/AccountListDropdown.tsx
  explorer/src/constants/index.ts
  explorer/src/constants/routes.ts
  explorer/src/constants/session.ts
  explorer/src/middleware.ts
  explorer/src/providers/ChainProvider.tsx
  explorer/src/providers/WalletProvider.tsx
  explorer/src/providers/index.tsx
  explorer/src/types/jwt.ts
  explorer/src/utils/auth/authOptions.ts
  explorer/src/utils/auth/providers/discord.ts
  explorer/src/utils/auth/providers/index.ts
  explorer/src/utils/auth/providers/nova.ts
  explorer/src/utils/auth/providers/subspace.ts
  explorer/src/utils/auth/vcs/discord/index.ts
  explorer/src/utils/auth/vcs/discord/member.ts
  explorer/src/utils/auth/vcs/discord/role-farmer.ts
  explorer/src/utils/auth/vcs/discord/utils.ts
  explorer/src/utils/auth/vcs/subspace/events-farmer.ts
  explorer/src/utils/auth/vcs/subspace/index.ts
  explorer/src/utils/queryGraphqlServer.ts
  explorer/yarn.lock
Labels: enhancement, Review effort [1-5]: 4
