Repository autonomys/astral, pull requests merged in 2024-05, with the labels that each got.

#579 Bug/fixSessionCookieForProdNetlify
  explorer/src/utils/auth/providers/discord.ts
Labels: Review effort [1-5]: 2, Bug fix

#576 Push staging to production
  .vscode/astral.code-workspace
  .vscode/settings.json
  README.md
  explorer/.env.sample
  explorer/.gitignore
  explorer/README.md
  explorer/gql/gql.ts
  explorer/gql/graphql.ts
  explorer/next-auth.d.ts
  explorer/package.json
  explorer/src/app/api/auth/[...nextauth]/route.ts
  explorer/src/components/Home/index.tsx
  explorer/src/components/Operator/ActionsDropdown.tsx
  explorer/src/components/Operator/ActionsModal.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/Operator/OperatorsListCard.tsx
  explorer/src/components/Operator/query.ts
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/WalletSideKick/query.ts
  explorer/src/components/icons/CheckMarkIcon.tsx
  explorer/src/components/icons/index.ts
  explorer/src/components/layout/AccountListDropdown.tsx
  explorer/src/constants/index.ts
  explorer/src/constants/routes.ts
  explorer/src/constants/session.ts
  explorer/src/middleware.ts
  explorer/src/providers/ChainProvider.tsx
  explorer/src/providers/WalletProvider.tsx
  explorer/src/providers/index.tsx
  explorer/src/types/jwt.ts
  explorer/src/utils/auth/authOptions.ts
  explorer/src/utils/auth/providers/discord.ts
  explorer/src/utils/auth/providers/index.ts
  explorer/src/utils/auth/providers/nova.ts
  explorer/src/utils/auth/providers/subspace.ts
  explorer/src/utils/auth/vcs/discord/index.ts
  explorer/src/utils/auth/vcs/discord/member.ts
  explorer/src/utils/auth/vcs/discord/role-farmer.ts
  explorer/src/utils/auth/vcs/discord/utils.ts
  explorer/src/utils/auth/vcs/subspace/events-farmer.ts
  explorer/src/utils/auth/vcs/subspace/index.ts
  explorer/src/utils/operator.ts
  explorer/src/utils/queryGraphqlServer.ts
  explorer/yarn.lock
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#583 Add missing Account Rewards page route
  explorer/src/app/[chain]/consensus/accounts/[accountId]/rewards/page.tsx
  explorer/src/components/Account/AccountRewardList.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#586 Add explainer for verified roles on WalletSidekick
  explorer/src/components/Operator/OperatorsListCard.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
Labels: enhancement, Review effort [1-5]: 3

#590 Fix staging merge conflict with main
  .github/workflows/gh-deploy-micro-squids.yml
  account-squid/.env.sample
  docker-compose-all-squids.yml
  explorer/src/components/Extrinsic/Extrinsic.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  general-squid/.env.sample
  indexers/account-squid/Dockerfile
  indexers/account-squid/docker-compose.yml
  indexers/general-squid/Dockerfile
  indexers/general-squid/docker-compose.yml
  indexers/rewards-squid/Dockerfile
  indexers/rewards-squid/docker-compose.yml
  rewards-squid/.env.sample
Labels: enhancement, Review effort [1-5]: 4, configuration changes, Bug fix

#592 Fix dockerfiles
  indexers/account-squid/Dockerfile
  indexers/general-squid/Dockerfile
  indexers/rewards-squid/Dockerfile
Labels: enhancement, Review effort [1-5]: 2

#595 Get verified roles section in walletsidekick is inconsistent
  explorer/src/components/Operator/OperatorsListCard.tsx
  explorer/src/components/WalletSideKick/GetDiscordRoles.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#604 Improve multi-squid to be link to the chain and allow for Astral to run against localhost
  explorer/.env.sample
  explorer/codegen.ts
  explorer/src/app/[chain]/consensus/accounts/[accountId]/image/route.tsx
  explorer/src/app/[chain]/image/route.tsx
  explorer/src/app/[chain]/nova/accounts/[accountId]/image/route.tsx
  explorer/src/components/WalletSideKick/AccountSummary.tsx
  explorer/src/components/WalletSideKick/LastExtrinsics.tsx
  explorer/src/components/WalletSideKick/StakingSummary.tsx
  explorer/src/components/layout/HeaderChainDropdown.tsx
  explorer/src/constants/chains.ts
  explorer/src/constants/domains.ts
  explorer/src/providers/ChainProvider.tsx
  explorer/src/utils/queryGraphqlServer.ts
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#602 Add more GA events to improve the understanding of users journey and behaviours
  explorer/src/components/Account/Account.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Operator/NominationManagement.tsx
  explorer/src/components/Operator/NominatorsList.tsx
  explorer/src/components/Operator/OperatorManagement.tsx
  explorer/src/components/Operator/OperatorsList.tsx
  explorer/src/components/WalletSideKick/ActionsButtons.tsx
  explorer/src/components/WalletSideKick/ActionsModal.tsx
  explorer/src/components/WalletSideKick/index.tsx
  explorer/src/components/common/SearchBar.tsx
  explorer/src/components/layout/Footer.tsx
  explorer/src/providers/WalletProvider.tsx
Labels: enhancement, Review effort [1-5]: 2, other
