Repository autonomys/astral, pull requests merged in 2024-08, with the labels that each got.

#787 fix rpc data following domains states changes
  explorer/src/hooks/useConsensusData.ts
  explorer/src/states/consensus.ts
  explorer/src/types/consensus.ts
Labels: Review effort [1-5]: 2, Bug fix

#785 Change some more subspace.network links for autonomys.xyz
  README.md
  explorer/next.config.js
  explorer/src/components/Farming/index.tsx
  explorer/src/constants/metadata.ts
  explorer/src/constants/routes.ts
  explorer/src/utils/auth/providers/nova.ts
  indexers/staking-squid/README.md
  indexers/staking-squid/package.json
Labels: documentation, enhancement, Review effort [1-5]: 2

#788 Change tx status to show fail extrinsic in red X
  explorer/src/components/WalletSideKick/PendingTransactions.tsx
  explorer/src/components/common/StatusIcon.tsx
Labels: enhancement, Review effort [1-5]: 2

#786 Integrate Staking-Squid to Staking-Interface
  explorer/codegen.ts
  explorer/gql/oldSquidTypes.ts
  explorer/gql/types/staking.ts
  explorer/src/components/Staking/ActionsDropdown.tsx
  explorer/src/components/Staking/MyWithdrawals.tsx
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorDetailsCard.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/query.ts
  explorer/src/components/Staking/staking.query.ts
  explorer/src/components/common/DataSource.tsx
  explorer/src/components/common/DataSourceBanner.tsx
  explorer/src/components/common/SortedTable.tsx
  explorer/src/components/common/TableNavigation.tsx
  explorer/src/constants/indexers.ts
  explorer/src/providers/ChainProvider.tsx
  explorer/src/states/query.ts
  explorer/src/utils/downloadFullData.ts
Labels: enhancement, Review effort [1-5]: 4

#790 Add a lot more details on operators, bundle and domains
  indexers/staking-squid/db/migrations/1722724863452-Data.js
  indexers/staking-squid/hasura/hasura_metadata.json
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/events/domain.ts
  indexers/staking-squid/src/events/epoch.ts
  indexers/staking-squid/src/events/index.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/events/withdraw.ts
  indexers/staking-squid/src/extrinsics/index.ts
  indexers/staking-squid/src/extrinsics/operator.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/storage/account.ts
  indexers/staking-squid/src/storage/bundle.ts
  indexers/staking-squid/src/storage/domain.ts
  indexers/staking-squid/src/storage/index.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/utils/cache.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 3, other, indexer

#803 Fix account list index and improve loading state on list
  explorer/src/components/Account/Account.tsx
  explorer/src/components/Account/AccountExtrinsicList.tsx
  explorer/src/components/Account/AccountList.tsx
  explorer/src/components/Account/AccountRewardList.tsx
  explorer/src/components/Block/Block.tsx
  explorer/src/components/Block/BlockDetailsEventList.tsx
  explorer/src/components/Block/BlockDetailsExtrinsicList.tsx
  explorer/src/components/Block/BlockList.tsx
  explorer/src/components/Event/Event.tsx
  explorer/src/components/Event/EventList.tsx
  explorer/src/components/Extrinsic/Extrinsic.tsx
  explorer/src/components/Extrinsic/ExtrinsicList.tsx
  explorer/src/components/Home/index.tsx
  explorer/src/components/Leaderboard/LeaderboardList.tsx
  explorer/src/components/Log/Log.tsx
  explorer/src/components/Log/LogList.tsx
  explorer/src/components/Staking/Operator.tsx
  explorer/src/components/Staking/OperatorNominatorTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 3, Bug fix

#804 Remove empty reward from all list query
  explorer/src/components/Account/query.ts
Labels: Review effort [1-5]: 2, Bug fix

#805 Fix extrinsics and events list on block details
  explorer/src/components/Block/BlockDetailsEventList.tsx
  explorer/src/components/Block/BlockDetailsExtrinsicList.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#796 Improve deposits and withdrawals on staking squid
  indexers/staking-squid/db/migrations/1723583832404-Data.js
  indexers/staking-squid/hasura/hasura_metadata.json
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/blocks/index.ts
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/events/domain.ts
  indexers/staking-squid/src/events/epoch.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/events/withdraw.ts
  indexers/staking-squid/src/extrinsics/operator.ts
  indexers/staking-squid/src/main.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/processor.ts
  indexers/staking-squid/src/storage/bundle.ts
  indexers/staking-squid/src/storage/nominator.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/utils/cache.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#810 fixes to hasura service docker compose
  indexers/squid-blockexplorer/docker-compose.yml
Labels: Review effort [1-5]: 1, configuration changes

#814 Staking squid v14
  indexers/staking-squid/db/migrations/1723776224429-Data.js
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/events/bundle.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/storage/bundle.ts
  indexers/staking-squid/src/storage/domainBlock.ts
  indexers/staking-squid/src/utils/cache.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, configuration changes, indexer

#812 Improve Auto-Id page
  explorer/.cursorrules
  explorer/src/components/AutoId/index.tsx
Labels: documentation, enhancement, Review effort [1-5]: 2

#815 Staking squid v15
  indexers/staking-squid/db/migrations/1723832727324-Data.js
  indexers/staking-squid/gemini3h.jsonl
  indexers/staking-squid/schema.graphql
  indexers/staking-squid/squid.yaml
  indexers/staking-squid/src/events/epoch.ts
  indexers/staking-squid/src/events/index.ts
  indexers/staking-squid/src/events/operator.ts
  indexers/staking-squid/src/events/unlock.ts
  indexers/staking-squid/src/events/withdraw.ts
  indexers/staking-squid/src/extrinsics/index.ts
  indexers/staking-squid/src/extrinsics/operator.ts
  indexers/staking-squid/src/model/generated/index.ts
  indexers/staking-squid/src/processor.ts
  indexers/staking-squid/src/storage/account.ts
  indexers/staking-squid/src/storage/deposit.ts
  indexers/staking-squid/src/storage/domain.ts
  indexers/staking-squid/src/storage/nominator.ts
  indexers/staking-squid/src/storage/operator.ts
  indexers/staking-squid/src/storage/stats.ts
  indexers/staking-squid/src/storage/withdrawal.ts
  indexers/staking-squid/src/types/domains/calls.ts
  indexers/staking-squid/src/types/domains/events.ts
  indexers/staking-squid/src/types/domains/storage.ts
  indexers/staking-squid/src/types/index.ts
  indexers/staking-squid/src/types/v6.ts
  indexers/staking-squid/src/utils/cache.ts
  indexers/staking-squid/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 5, tests, indexer

#817 Feat/implement staking squidv15
  explorer/gql/types/staking.ts
  explorer/src/components/Domain/DomainBlockTimeProgress.tsx
  explorer/src/components/Domain/DomainsList.tsx
  explorer/src/components/Domain/staking.query.ts
  explorer/src/components/Staking/NominationsTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/staking.query.ts
  explorer/src/components/common/DesktopTable.tsx
  explorer/src/components/common/SortedTable.tsx
  explorer/src/constants/indexers.ts
  explorer/src/constants/tables.ts
  explorer/src/utils/number.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#827 Fix Tooltip
  explorer/src/components/common/Tooltip.tsx
Labels: Review effort [1-5]: 1, bug_fix, Bug fix

#829 Raw status is mention twice in operators table editor
  explorer/src/constants/tables.ts
Labels: Review effort [1-5]: 1, Bug fix

#833 Memoize Apollo client to avoid the client re-render (canceling request from previous client in the process)
  explorer/src/providers/ChainProvider.tsx
Labels: enhancement, Review effort [1-5]: 2

#831 Fix z-index issue on Nominators page
  explorer/src/components/Staking/ActionsDropdown.tsx
Labels: bug_fix, Review effort [1-5]: 2, Bug fix

#838 Its possible to nominate a slashed or deregistered op
  explorer/gql/types/staking.ts
  explorer/src/components/Staking/NominationsTable.tsx
  explorer/src/components/Staking/OperatorsList.tsx
  explorer/src/components/Staking/staking.query.ts
  explorer/src/constants/staking.ts
  explorer/src/constants/tables.ts
  explorer/src/states/tables.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#826 Prevent a larger amount to be calculated
  explorer/src/components/Staking/ActionsModal.tsx
Labels: Review effort [1-5]: 2, Bug fix
